// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.0
// source: message/analytics.proto

package message

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetTaskDashboardKPIRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeriodFrom    *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=period_from,json=periodFrom,proto3,oneof" json:"period_from,omitempty"`
	PeriodTo      *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=period_to,json=periodTo,proto3,oneof" json:"period_to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskDashboardKPIRequest) Reset() {
	*x = GetTaskDashboardKPIRequest{}
	mi := &file_message_analytics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskDashboardKPIRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskDashboardKPIRequest) ProtoMessage() {}

func (x *GetTaskDashboardKPIRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_analytics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskDashboardKPIRequest.ProtoReflect.Descriptor instead.
func (*GetTaskDashboardKPIRequest) Descriptor() ([]byte, []int) {
	return file_message_analytics_proto_rawDescGZIP(), []int{0}
}

func (x *GetTaskDashboardKPIRequest) GetPeriodFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.PeriodFrom
	}
	return nil
}

func (x *GetTaskDashboardKPIRequest) GetPeriodTo() *timestamppb.Timestamp {
	if x != nil {
		return x.PeriodTo
	}
	return nil
}

type GetTaskDashboardKPIResponse struct {
	state                   protoimpl.MessageState                              `protogen:"open.v1"`
	ActiveTasksCount        int64                                               `protobuf:"varint,1,opt,name=active_tasks_count,json=activeTasksCount,proto3" json:"active_tasks_count,omitempty"`
	CompletedInPeriod       int64                                               `protobuf:"varint,2,opt,name=completed_in_period,json=completedInPeriod,proto3" json:"completed_in_period,omitempty"`
	CreatedInPeriod         int64                                               `protobuf:"varint,3,opt,name=created_in_period,json=createdInPeriod,proto3" json:"created_in_period,omitempty"`
	CompletedToCreatedRatio *float64                                            `protobuf:"fixed64,4,opt,name=completed_to_created_ratio,json=completedToCreatedRatio,proto3,oneof" json:"completed_to_created_ratio,omitempty"`
	TopExecutor             *GetTaskDashboardKPIResponse_TopExecutorByCompleted `protobuf:"bytes,5,opt,name=top_executor,json=topExecutor,proto3,oneof" json:"top_executor,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *GetTaskDashboardKPIResponse) Reset() {
	*x = GetTaskDashboardKPIResponse{}
	mi := &file_message_analytics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskDashboardKPIResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskDashboardKPIResponse) ProtoMessage() {}

func (x *GetTaskDashboardKPIResponse) ProtoReflect() protoreflect.Message {
	mi := &file_message_analytics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskDashboardKPIResponse.ProtoReflect.Descriptor instead.
func (*GetTaskDashboardKPIResponse) Descriptor() ([]byte, []int) {
	return file_message_analytics_proto_rawDescGZIP(), []int{1}
}

func (x *GetTaskDashboardKPIResponse) GetActiveTasksCount() int64 {
	if x != nil {
		return x.ActiveTasksCount
	}
	return 0
}

func (x *GetTaskDashboardKPIResponse) GetCompletedInPeriod() int64 {
	if x != nil {
		return x.CompletedInPeriod
	}
	return 0
}

func (x *GetTaskDashboardKPIResponse) GetCreatedInPeriod() int64 {
	if x != nil {
		return x.CreatedInPeriod
	}
	return 0
}

func (x *GetTaskDashboardKPIResponse) GetCompletedToCreatedRatio() float64 {
	if x != nil && x.CompletedToCreatedRatio != nil {
		return *x.CompletedToCreatedRatio
	}
	return 0
}

func (x *GetTaskDashboardKPIResponse) GetTopExecutor() *GetTaskDashboardKPIResponse_TopExecutorByCompleted {
	if x != nil {
		return x.TopExecutor
	}
	return nil
}

type GetTaskDashboardKPIResponse_TopExecutorByCompleted struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ExecutorId     int64                  `protobuf:"varint,1,opt,name=executor_id,json=executorId,proto3" json:"executor_id,omitempty"`
	ExecutorName   string                 `protobuf:"bytes,2,opt,name=executor_name,json=executorName,proto3" json:"executor_name,omitempty"`
	CompletedTasks int64                  `protobuf:"varint,3,opt,name=completed_tasks,json=completedTasks,proto3" json:"completed_tasks,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetTaskDashboardKPIResponse_TopExecutorByCompleted) Reset() {
	*x = GetTaskDashboardKPIResponse_TopExecutorByCompleted{}
	mi := &file_message_analytics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskDashboardKPIResponse_TopExecutorByCompleted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskDashboardKPIResponse_TopExecutorByCompleted) ProtoMessage() {}

func (x *GetTaskDashboardKPIResponse_TopExecutorByCompleted) ProtoReflect() protoreflect.Message {
	mi := &file_message_analytics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskDashboardKPIResponse_TopExecutorByCompleted.ProtoReflect.Descriptor instead.
func (*GetTaskDashboardKPIResponse_TopExecutorByCompleted) Descriptor() ([]byte, []int) {
	return file_message_analytics_proto_rawDescGZIP(), []int{1, 0}
}

func (x *GetTaskDashboardKPIResponse_TopExecutorByCompleted) GetExecutorId() int64 {
	if x != nil {
		return x.ExecutorId
	}
	return 0
}

func (x *GetTaskDashboardKPIResponse_TopExecutorByCompleted) GetExecutorName() string {
	if x != nil {
		return x.ExecutorName
	}
	return ""
}

func (x *GetTaskDashboardKPIResponse_TopExecutorByCompleted) GetCompletedTasks() int64 {
	if x != nil {
		return x.CompletedTasks
	}
	return 0
}

var File_message_analytics_proto protoreflect.FileDescriptor

const file_message_analytics_proto_rawDesc = "" +
	"\n" +
	"\x17message/analytics.proto\x12\bguard.v1\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xba\x01\n" +
	"\x1aGetTaskDashboardKPIRequest\x12@\n" +
	"\vperiod_from\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\n" +
	"periodFrom\x88\x01\x01\x12<\n" +
	"\tperiod_to\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampH\x01R\bperiodTo\x88\x01\x01B\x0e\n" +
	"\f_period_fromB\f\n" +
	"\n" +
	"_period_to\"\x98\x04\n" +
	"\x1bGetTaskDashboardKPIResponse\x12,\n" +
	"\x12active_tasks_count\x18\x01 \x01(\x03R\x10activeTasksCount\x12.\n" +
	"\x13completed_in_period\x18\x02 \x01(\x03R\x11completedInPeriod\x12*\n" +
	"\x11created_in_period\x18\x03 \x01(\x03R\x0fcreatedInPeriod\x12@\n" +
	"\x1acompleted_to_created_ratio\x18\x04 \x01(\x01H\x00R\x17completedToCreatedRatio\x88\x01\x01\x12d\n" +
	"\ftop_executor\x18\x05 \x01(\v2<.guard.v1.GetTaskDashboardKPIResponse.TopExecutorByCompletedH\x01R\vtopExecutor\x88\x01\x01\x1a\x96\x01\n" +
	"\x16TopExecutorByCompleted\x12$\n" +
	"\vexecutor_id\x18\x01 \x01(\x03B\x03\xe0A\x02R\n" +
	"executorId\x12(\n" +
	"\rexecutor_name\x18\x02 \x01(\tB\x03\xe0A\x02R\fexecutorName\x12,\n" +
	"\x0fcompleted_tasks\x18\x03 \x01(\x03B\x03\xe0A\x02R\x0ecompletedTasksB\x1d\n" +
	"\x1b_completed_to_created_ratioB\x0f\n" +
	"\r_top_executorB=Z;github.com/gigasigmaslav/guard-panel-api/pkg/api/v1/messageb\x06proto3"

var (
	file_message_analytics_proto_rawDescOnce sync.Once
	file_message_analytics_proto_rawDescData []byte
)

func file_message_analytics_proto_rawDescGZIP() []byte {
	file_message_analytics_proto_rawDescOnce.Do(func() {
		file_message_analytics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_message_analytics_proto_rawDesc), len(file_message_analytics_proto_rawDesc)))
	})
	return file_message_analytics_proto_rawDescData
}

var file_message_analytics_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_message_analytics_proto_goTypes = []any{
	(*GetTaskDashboardKPIRequest)(nil),                         // 0: guard.v1.GetTaskDashboardKPIRequest
	(*GetTaskDashboardKPIResponse)(nil),                        // 1: guard.v1.GetTaskDashboardKPIResponse
	(*GetTaskDashboardKPIResponse_TopExecutorByCompleted)(nil), // 2: guard.v1.GetTaskDashboardKPIResponse.TopExecutorByCompleted
	(*timestamppb.Timestamp)(nil),                              // 3: google.protobuf.Timestamp
}
var file_message_analytics_proto_depIdxs = []int32{
	3, // 0: guard.v1.GetTaskDashboardKPIRequest.period_from:type_name -> google.protobuf.Timestamp
	3, // 1: guard.v1.GetTaskDashboardKPIRequest.period_to:type_name -> google.protobuf.Timestamp
	2, // 2: guard.v1.GetTaskDashboardKPIResponse.top_executor:type_name -> guard.v1.GetTaskDashboardKPIResponse.TopExecutorByCompleted
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_message_analytics_proto_init() }
func file_message_analytics_proto_init() {
	if File_message_analytics_proto != nil {
		return
	}
	file_message_analytics_proto_msgTypes[0].OneofWrappers = []any{}
	file_message_analytics_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_message_analytics_proto_rawDesc), len(file_message_analytics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_message_analytics_proto_goTypes,
		DependencyIndexes: file_message_analytics_proto_depIdxs,
		MessageInfos:      file_message_analytics_proto_msgTypes,
	}.Build()
	File_message_analytics_proto = out.File
	file_message_analytics_proto_goTypes = nil
	file_message_analytics_proto_depIdxs = nil
}
