// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.0
// source: message/auth.proto

package message

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SignUpRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EmployeeId    int64                  `protobuf:"varint,1,opt,name=employee_id,json=employeeId,proto3" json:"employee_id,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignUpRequest) Reset() {
	*x = SignUpRequest{}
	mi := &file_message_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignUpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignUpRequest) ProtoMessage() {}

func (x *SignUpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignUpRequest.ProtoReflect.Descriptor instead.
func (*SignUpRequest) Descriptor() ([]byte, []int) {
	return file_message_auth_proto_rawDescGZIP(), []int{0}
}

func (x *SignUpRequest) GetEmployeeId() int64 {
	if x != nil {
		return x.EmployeeId
	}
	return 0
}

func (x *SignUpRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type SignInRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EmployeeId    int64                  `protobuf:"varint,1,opt,name=employee_id,json=employeeId,proto3" json:"employee_id,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignInRequest) Reset() {
	*x = SignInRequest{}
	mi := &file_message_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignInRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignInRequest) ProtoMessage() {}

func (x *SignInRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignInRequest.ProtoReflect.Descriptor instead.
func (*SignInRequest) Descriptor() ([]byte, []int) {
	return file_message_auth_proto_rawDescGZIP(), []int{1}
}

func (x *SignInRequest) GetEmployeeId() int64 {
	if x != nil {
		return x.EmployeeId
	}
	return 0
}

func (x *SignInRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type AuthTokensResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthTokensResponse) Reset() {
	*x = AuthTokensResponse{}
	mi := &file_message_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthTokensResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthTokensResponse) ProtoMessage() {}

func (x *AuthTokensResponse) ProtoReflect() protoreflect.Message {
	mi := &file_message_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthTokensResponse.ProtoReflect.Descriptor instead.
func (*AuthTokensResponse) Descriptor() ([]byte, []int) {
	return file_message_auth_proto_rawDescGZIP(), []int{2}
}

func (x *AuthTokensResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *AuthTokensResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type WhoAmIResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EmployeeId    int64                  `protobuf:"varint,1,opt,name=employee_id,json=employeeId,proto3" json:"employee_id,omitempty"`
	FullName      string                 `protobuf:"bytes,2,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	Position      EmployeePosition       `protobuf:"varint,3,opt,name=position,proto3,enum=guard.v1.EmployeePosition" json:"position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WhoAmIResponse) Reset() {
	*x = WhoAmIResponse{}
	mi := &file_message_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WhoAmIResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WhoAmIResponse) ProtoMessage() {}

func (x *WhoAmIResponse) ProtoReflect() protoreflect.Message {
	mi := &file_message_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WhoAmIResponse.ProtoReflect.Descriptor instead.
func (*WhoAmIResponse) Descriptor() ([]byte, []int) {
	return file_message_auth_proto_rawDescGZIP(), []int{3}
}

func (x *WhoAmIResponse) GetEmployeeId() int64 {
	if x != nil {
		return x.EmployeeId
	}
	return 0
}

func (x *WhoAmIResponse) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *WhoAmIResponse) GetPosition() EmployeePosition {
	if x != nil {
		return x.Position
	}
	return EmployeePosition_EMPLOYEE_POSITION_UNSPECIFIED
}

var File_message_auth_proto protoreflect.FileDescriptor

const file_message_auth_proto_rawDesc = "" +
	"\n" +
	"\x12message/auth.proto\x12\bguard.v1\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x17validate/validate.proto\x1a\x14message/common.proto\"g\n" +
	"\rSignUpRequest\x12+\n" +
	"\vemployee_id\x18\x01 \x01(\x03B\n" +
	"\xe0A\x02\xfaB\x04\"\x02 \x00R\n" +
	"employeeId\x12)\n" +
	"\bpassword\x18\x02 \x01(\tB\r\xe0A\x02\xfaB\ar\x05\x10\b\x18\x80\x02R\bpassword\"g\n" +
	"\rSignInRequest\x12+\n" +
	"\vemployee_id\x18\x01 \x01(\x03B\n" +
	"\xe0A\x02\xfaB\x04\"\x02 \x00R\n" +
	"employeeId\x12)\n" +
	"\bpassword\x18\x02 \x01(\tB\r\xe0A\x02\xfaB\ar\x05\x10\x01\x18\x80\x02R\bpassword\"r\n" +
	"\x12AuthTokensResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x129\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"\x86\x01\n" +
	"\x0eWhoAmIResponse\x12\x1f\n" +
	"\vemployee_id\x18\x01 \x01(\x03R\n" +
	"employeeId\x12\x1b\n" +
	"\tfull_name\x18\x02 \x01(\tR\bfullName\x126\n" +
	"\bposition\x18\x03 \x01(\x0e2\x1a.guard.v1.EmployeePositionR\bpositionB=Z;github.com/gigasigmaslav/guard-panel-api/pkg/api/v1/messageb\x06proto3"

var (
	file_message_auth_proto_rawDescOnce sync.Once
	file_message_auth_proto_rawDescData []byte
)

func file_message_auth_proto_rawDescGZIP() []byte {
	file_message_auth_proto_rawDescOnce.Do(func() {
		file_message_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_message_auth_proto_rawDesc), len(file_message_auth_proto_rawDesc)))
	})
	return file_message_auth_proto_rawDescData
}

var file_message_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_message_auth_proto_goTypes = []any{
	(*SignUpRequest)(nil),         // 0: guard.v1.SignUpRequest
	(*SignInRequest)(nil),         // 1: guard.v1.SignInRequest
	(*AuthTokensResponse)(nil),    // 2: guard.v1.AuthTokensResponse
	(*WhoAmIResponse)(nil),        // 3: guard.v1.WhoAmIResponse
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
	(EmployeePosition)(0),         // 5: guard.v1.EmployeePosition
}
var file_message_auth_proto_depIdxs = []int32{
	4, // 0: guard.v1.AuthTokensResponse.expires_at:type_name -> google.protobuf.Timestamp
	5, // 1: guard.v1.WhoAmIResponse.position:type_name -> guard.v1.EmployeePosition
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_message_auth_proto_init() }
func file_message_auth_proto_init() {
	if File_message_auth_proto != nil {
		return
	}
	file_message_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_message_auth_proto_rawDesc), len(file_message_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_message_auth_proto_goTypes,
		DependencyIndexes: file_message_auth_proto_depIdxs,
		MessageInfos:      file_message_auth_proto_msgTypes,
	}.Build()
	File_message_auth_proto = out.File
	file_message_auth_proto_goTypes = nil
	file_message_auth_proto_depIdxs = nil
}
