// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.0
// source: message/common.proto

package message

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Enums
type TaskStatus int32

const (
	TaskStatus_CASE_STATUS_UNSPECIFIED TaskStatus = 0
	TaskStatus_NEW                     TaskStatus = 1
	TaskStatus_DOCUMENT_GATHERING      TaskStatus = 2
	TaskStatus_WAITING_FOR_VUD         TaskStatus = 3
	TaskStatus_JUDICIAL_PROCEEDINGS    TaskStatus = 4
	TaskStatus_COMPLETED               TaskStatus = 5
)

// Enum value maps for TaskStatus.
var (
	TaskStatus_name = map[int32]string{
		0: "CASE_STATUS_UNSPECIFIED",
		1: "NEW",
		2: "DOCUMENT_GATHERING",
		3: "WAITING_FOR_VUD",
		4: "JUDICIAL_PROCEEDINGS",
		5: "COMPLETED",
	}
	TaskStatus_value = map[string]int32{
		"CASE_STATUS_UNSPECIFIED": 0,
		"NEW":                     1,
		"DOCUMENT_GATHERING":      2,
		"WAITING_FOR_VUD":         3,
		"JUDICIAL_PROCEEDINGS":    4,
		"COMPLETED":               5,
	}
)

func (x TaskStatus) Enum() *TaskStatus {
	p := new(TaskStatus)
	*p = x
	return p
}

func (x TaskStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_message_common_proto_enumTypes[0].Descriptor()
}

func (TaskStatus) Type() protoreflect.EnumType {
	return &file_message_common_proto_enumTypes[0]
}

func (x TaskStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskStatus.Descriptor instead.
func (TaskStatus) EnumDescriptor() ([]byte, []int) {
	return file_message_common_proto_rawDescGZIP(), []int{0}
}

type EmployeePosition int32

const (
	EmployeePosition_EMPLOYEE_POSITION_UNSPECIFIED EmployeePosition = 0
	EmployeePosition_SEC                           EmployeePosition = 1
	EmployeePosition_SEC_HEAD                      EmployeePosition = 2
)

// Enum value maps for EmployeePosition.
var (
	EmployeePosition_name = map[int32]string{
		0: "EMPLOYEE_POSITION_UNSPECIFIED",
		1: "SEC",
		2: "SEC_HEAD",
	}
	EmployeePosition_value = map[string]int32{
		"EMPLOYEE_POSITION_UNSPECIFIED": 0,
		"SEC":                           1,
		"SEC_HEAD":                      2,
	}
)

func (x EmployeePosition) Enum() *EmployeePosition {
	p := new(EmployeePosition)
	*p = x
	return p
}

func (x EmployeePosition) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EmployeePosition) Descriptor() protoreflect.EnumDescriptor {
	return file_message_common_proto_enumTypes[1].Descriptor()
}

func (EmployeePosition) Type() protoreflect.EnumType {
	return &file_message_common_proto_enumTypes[1]
}

func (x EmployeePosition) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EmployeePosition.Descriptor instead.
func (EmployeePosition) EnumDescriptor() ([]byte, []int) {
	return file_message_common_proto_rawDescGZIP(), []int{1}
}

type TaskPriority int32

const (
	TaskPriority_TASK_PRIORITY_UNSPECIFIED TaskPriority = 0
	TaskPriority_LOW                       TaskPriority = 1
	TaskPriority_HIGH                      TaskPriority = 2
)

// Enum value maps for TaskPriority.
var (
	TaskPriority_name = map[int32]string{
		0: "TASK_PRIORITY_UNSPECIFIED",
		1: "LOW",
		2: "HIGH",
	}
	TaskPriority_value = map[string]int32{
		"TASK_PRIORITY_UNSPECIFIED": 0,
		"LOW":                       1,
		"HIGH":                      2,
	}
)

func (x TaskPriority) Enum() *TaskPriority {
	p := new(TaskPriority)
	*p = x
	return p
}

func (x TaskPriority) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskPriority) Descriptor() protoreflect.EnumDescriptor {
	return file_message_common_proto_enumTypes[2].Descriptor()
}

func (TaskPriority) Type() protoreflect.EnumType {
	return &file_message_common_proto_enumTypes[2]
}

func (x TaskPriority) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskPriority.Descriptor instead.
func (TaskPriority) EnumDescriptor() ([]byte, []int) {
	return file_message_common_proto_rawDescGZIP(), []int{2}
}

type ViolatorType int32

const (
	ViolatorType_VIOLATOR_TYPE_UNSPECIFIED ViolatorType = 0
	ViolatorType_EMPLOYEE                  ViolatorType = 1
	ViolatorType_CLIENT                    ViolatorType = 2
)

// Enum value maps for ViolatorType.
var (
	ViolatorType_name = map[int32]string{
		0: "VIOLATOR_TYPE_UNSPECIFIED",
		1: "EMPLOYEE",
		2: "CLIENT",
	}
	ViolatorType_value = map[string]int32{
		"VIOLATOR_TYPE_UNSPECIFIED": 0,
		"EMPLOYEE":                  1,
		"CLIENT":                    2,
	}
)

func (x ViolatorType) Enum() *ViolatorType {
	p := new(ViolatorType)
	*p = x
	return p
}

func (x ViolatorType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ViolatorType) Descriptor() protoreflect.EnumDescriptor {
	return file_message_common_proto_enumTypes[3].Descriptor()
}

func (ViolatorType) Type() protoreflect.EnumType {
	return &file_message_common_proto_enumTypes[3]
}

func (x ViolatorType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ViolatorType.Descriptor instead.
func (ViolatorType) EnumDescriptor() ([]byte, []int) {
	return file_message_common_proto_rawDescGZIP(), []int{3}
}

type OrderDirection int32

const (
	OrderDirection_ORDER_DIRECTION_UNSPECIFIED OrderDirection = 0
	OrderDirection_ASC                         OrderDirection = 1
	OrderDirection_DESC                        OrderDirection = 2
)

// Enum value maps for OrderDirection.
var (
	OrderDirection_name = map[int32]string{
		0: "ORDER_DIRECTION_UNSPECIFIED",
		1: "ASC",
		2: "DESC",
	}
	OrderDirection_value = map[string]int32{
		"ORDER_DIRECTION_UNSPECIFIED": 0,
		"ASC":                         1,
		"DESC":                        2,
	}
)

func (x OrderDirection) Enum() *OrderDirection {
	p := new(OrderDirection)
	*p = x
	return p
}

func (x OrderDirection) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderDirection) Descriptor() protoreflect.EnumDescriptor {
	return file_message_common_proto_enumTypes[4].Descriptor()
}

func (OrderDirection) Type() protoreflect.EnumType {
	return &file_message_common_proto_enumTypes[4]
}

func (x OrderDirection) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderDirection.Descriptor instead.
func (OrderDirection) EnumDescriptor() ([]byte, []int) {
	return file_message_common_proto_rawDescGZIP(), []int{4}
}

type OrderBy int32

const (
	OrderBy_ORDER_BY_UNSPECIFIED   OrderBy = 0
	OrderBy_BARCODES_DAMAGE_AMOUNT OrderBy = 1
	OrderBy_CREATED_AT             OrderBy = 2
)

// Enum value maps for OrderBy.
var (
	OrderBy_name = map[int32]string{
		0: "ORDER_BY_UNSPECIFIED",
		1: "BARCODES_DAMAGE_AMOUNT",
		2: "CREATED_AT",
	}
	OrderBy_value = map[string]int32{
		"ORDER_BY_UNSPECIFIED":   0,
		"BARCODES_DAMAGE_AMOUNT": 1,
		"CREATED_AT":             2,
	}
)

func (x OrderBy) Enum() *OrderBy {
	p := new(OrderBy)
	*p = x
	return p
}

func (x OrderBy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderBy) Descriptor() protoreflect.EnumDescriptor {
	return file_message_common_proto_enumTypes[5].Descriptor()
}

func (OrderBy) Type() protoreflect.EnumType {
	return &file_message_common_proto_enumTypes[5]
}

func (x OrderBy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderBy.Descriptor instead.
func (OrderBy) EnumDescriptor() ([]byte, []int) {
	return file_message_common_proto_rawDescGZIP(), []int{5}
}

// Messages
type GetByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetByIDRequest) Reset() {
	*x = GetByIDRequest{}
	mi := &file_message_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByIDRequest) ProtoMessage() {}

func (x *GetByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByIDRequest.ProtoReflect.Descriptor instead.
func (*GetByIDRequest) Descriptor() ([]byte, []int) {
	return file_message_common_proto_rawDescGZIP(), []int{0}
}

func (x *GetByIDRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteByIDRequest) Reset() {
	*x = DeleteByIDRequest{}
	mi := &file_message_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteByIDRequest) ProtoMessage() {}

func (x *DeleteByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteByIDRequest.ProtoReflect.Descriptor instead.
func (*DeleteByIDRequest) Descriptor() ([]byte, []int) {
	return file_message_common_proto_rawDescGZIP(), []int{1}
}

func (x *DeleteByIDRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type CreatedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatedResponse) Reset() {
	*x = CreatedResponse{}
	mi := &file_message_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatedResponse) ProtoMessage() {}

func (x *CreatedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_message_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatedResponse.ProtoReflect.Descriptor instead.
func (*CreatedResponse) Descriptor() ([]byte, []int) {
	return file_message_common_proto_rawDescGZIP(), []int{2}
}

func (x *CreatedResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// Lookups
type Lookup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Lookup) Reset() {
	*x = Lookup{}
	mi := &file_message_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Lookup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Lookup) ProtoMessage() {}

func (x *Lookup) ProtoReflect() protoreflect.Message {
	mi := &file_message_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Lookup.ProtoReflect.Descriptor instead.
func (*Lookup) Descriptor() ([]byte, []int) {
	return file_message_common_proto_rawDescGZIP(), []int{3}
}

func (x *Lookup) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Lookup) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Sorting
type Sorting struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrderDirection OrderDirection         `protobuf:"varint,1,opt,name=order_direction,json=orderDirection,proto3,enum=guard.v1.OrderDirection" json:"order_direction,omitempty"`
	OrderBy        OrderBy                `protobuf:"varint,2,opt,name=order_by,json=orderBy,proto3,enum=guard.v1.OrderBy" json:"order_by,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Sorting) Reset() {
	*x = Sorting{}
	mi := &file_message_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sorting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sorting) ProtoMessage() {}

func (x *Sorting) ProtoReflect() protoreflect.Message {
	mi := &file_message_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sorting.ProtoReflect.Descriptor instead.
func (*Sorting) Descriptor() ([]byte, []int) {
	return file_message_common_proto_rawDescGZIP(), []int{4}
}

func (x *Sorting) GetOrderDirection() OrderDirection {
	if x != nil {
		return x.OrderDirection
	}
	return OrderDirection_ORDER_DIRECTION_UNSPECIFIED
}

func (x *Sorting) GetOrderBy() OrderBy {
	if x != nil {
		return x.OrderBy
	}
	return OrderBy_ORDER_BY_UNSPECIFIED
}

var File_message_common_proto protoreflect.FileDescriptor

const file_message_common_proto_rawDesc = "" +
	"\n" +
	"\x14message/common.proto\x12\bguard.v1\x1a google/protobuf/descriptor.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x17validate/validate.proto\" \n" +
	"\x0eGetByIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"#\n" +
	"\x11DeleteByIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"!\n" +
	"\x0fCreatedResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\",\n" +
	"\x06Lookup\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\x94\x01\n" +
	"\aSorting\x12N\n" +
	"\x0forder_direction\x18\x01 \x01(\x0e2\x18.guard.v1.OrderDirectionB\v\xe0A\x02\xfaB\x05\x82\x01\x02\x10\x01R\x0eorderDirection\x129\n" +
	"\border_by\x18\x02 \x01(\x0e2\x11.guard.v1.OrderByB\v\xe0A\x02\xfaB\x05\x82\x01\x02\x10\x01R\aorderBy*\x88\x01\n" +
	"\n" +
	"TaskStatus\x12\x1b\n" +
	"\x17CASE_STATUS_UNSPECIFIED\x10\x00\x12\a\n" +
	"\x03NEW\x10\x01\x12\x16\n" +
	"\x12DOCUMENT_GATHERING\x10\x02\x12\x13\n" +
	"\x0fWAITING_FOR_VUD\x10\x03\x12\x18\n" +
	"\x14JUDICIAL_PROCEEDINGS\x10\x04\x12\r\n" +
	"\tCOMPLETED\x10\x05*L\n" +
	"\x10EmployeePosition\x12!\n" +
	"\x1dEMPLOYEE_POSITION_UNSPECIFIED\x10\x00\x12\a\n" +
	"\x03SEC\x10\x01\x12\f\n" +
	"\bSEC_HEAD\x10\x02*@\n" +
	"\fTaskPriority\x12\x1d\n" +
	"\x19TASK_PRIORITY_UNSPECIFIED\x10\x00\x12\a\n" +
	"\x03LOW\x10\x01\x12\b\n" +
	"\x04HIGH\x10\x02*G\n" +
	"\fViolatorType\x12\x1d\n" +
	"\x19VIOLATOR_TYPE_UNSPECIFIED\x10\x00\x12\f\n" +
	"\bEMPLOYEE\x10\x01\x12\n" +
	"\n" +
	"\x06CLIENT\x10\x02*D\n" +
	"\x0eOrderDirection\x12\x1f\n" +
	"\x1bORDER_DIRECTION_UNSPECIFIED\x10\x00\x12\a\n" +
	"\x03ASC\x10\x01\x12\b\n" +
	"\x04DESC\x10\x02*O\n" +
	"\aOrderBy\x12\x18\n" +
	"\x14ORDER_BY_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16BARCODES_DAMAGE_AMOUNT\x10\x01\x12\x0e\n" +
	"\n" +
	"CREATED_AT\x10\x02B=Z;github.com/gigasigmaslav/guard-panel-api/pkg/api/v1/messageb\x06proto3"

var (
	file_message_common_proto_rawDescOnce sync.Once
	file_message_common_proto_rawDescData []byte
)

func file_message_common_proto_rawDescGZIP() []byte {
	file_message_common_proto_rawDescOnce.Do(func() {
		file_message_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_message_common_proto_rawDesc), len(file_message_common_proto_rawDesc)))
	})
	return file_message_common_proto_rawDescData
}

var file_message_common_proto_enumTypes = make([]protoimpl.EnumInfo, 6)
var file_message_common_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_message_common_proto_goTypes = []any{
	(TaskStatus)(0),           // 0: guard.v1.TaskStatus
	(EmployeePosition)(0),     // 1: guard.v1.EmployeePosition
	(TaskPriority)(0),         // 2: guard.v1.TaskPriority
	(ViolatorType)(0),         // 3: guard.v1.ViolatorType
	(OrderDirection)(0),       // 4: guard.v1.OrderDirection
	(OrderBy)(0),              // 5: guard.v1.OrderBy
	(*GetByIDRequest)(nil),    // 6: guard.v1.GetByIDRequest
	(*DeleteByIDRequest)(nil), // 7: guard.v1.DeleteByIDRequest
	(*CreatedResponse)(nil),   // 8: guard.v1.CreatedResponse
	(*Lookup)(nil),            // 9: guard.v1.Lookup
	(*Sorting)(nil),           // 10: guard.v1.Sorting
}
var file_message_common_proto_depIdxs = []int32{
	4, // 0: guard.v1.Sorting.order_direction:type_name -> guard.v1.OrderDirection
	5, // 1: guard.v1.Sorting.order_by:type_name -> guard.v1.OrderBy
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_message_common_proto_init() }
func file_message_common_proto_init() {
	if File_message_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_message_common_proto_rawDesc), len(file_message_common_proto_rawDesc)),
			NumEnums:      6,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_message_common_proto_goTypes,
		DependencyIndexes: file_message_common_proto_depIdxs,
		EnumInfos:         file_message_common_proto_enumTypes,
		MessageInfos:      file_message_common_proto_msgTypes,
	}.Build()
	File_message_common_proto = out.File
	file_message_common_proto_goTypes = nil
	file_message_common_proto_depIdxs = nil
}
