// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: message/common.proto

package message

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on GetByIDRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *GetByIDRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetByIDRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in GetByIDRequestMultiError,
// or nil if none found.
func (m *GetByIDRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetByIDRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if len(errors) > 0 {
		return GetByIDRequestMultiError(errors)
	}

	return nil
}

// GetByIDRequestMultiError is an error wrapping multiple validation errors
// returned by GetByIDRequest.ValidateAll() if the designated constraints
// aren't met.
type GetByIDRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetByIDRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetByIDRequestMultiError) AllErrors() []error { return m }

// GetByIDRequestValidationError is the validation error returned by
// GetByIDRequest.Validate if the designated constraints aren't met.
type GetByIDRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetByIDRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetByIDRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetByIDRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetByIDRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetByIDRequestValidationError) ErrorName() string { return "GetByIDRequestValidationError" }

// Error satisfies the builtin error interface
func (e GetByIDRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetByIDRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetByIDRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetByIDRequestValidationError{}

// Validate checks the field values on DeleteByIDRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *DeleteByIDRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteByIDRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteByIDRequestMultiError, or nil if none found.
func (m *DeleteByIDRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteByIDRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if len(errors) > 0 {
		return DeleteByIDRequestMultiError(errors)
	}

	return nil
}

// DeleteByIDRequestMultiError is an error wrapping multiple validation errors
// returned by DeleteByIDRequest.ValidateAll() if the designated constraints
// aren't met.
type DeleteByIDRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteByIDRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteByIDRequestMultiError) AllErrors() []error { return m }

// DeleteByIDRequestValidationError is the validation error returned by
// DeleteByIDRequest.Validate if the designated constraints aren't met.
type DeleteByIDRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteByIDRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteByIDRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteByIDRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteByIDRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteByIDRequestValidationError) ErrorName() string {
	return "DeleteByIDRequestValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteByIDRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteByIDRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteByIDRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteByIDRequestValidationError{}

// Validate checks the field values on CreatedResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *CreatedResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreatedResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreatedResponseMultiError, or nil if none found.
func (m *CreatedResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *CreatedResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if len(errors) > 0 {
		return CreatedResponseMultiError(errors)
	}

	return nil
}

// CreatedResponseMultiError is an error wrapping multiple validation errors
// returned by CreatedResponse.ValidateAll() if the designated constraints
// aren't met.
type CreatedResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreatedResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreatedResponseMultiError) AllErrors() []error { return m }

// CreatedResponseValidationError is the validation error returned by
// CreatedResponse.Validate if the designated constraints aren't met.
type CreatedResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreatedResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreatedResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreatedResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreatedResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreatedResponseValidationError) ErrorName() string { return "CreatedResponseValidationError" }

// Error satisfies the builtin error interface
func (e CreatedResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreatedResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreatedResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreatedResponseValidationError{}

// Validate checks the field values on Lookup with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Lookup) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Lookup with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in LookupMultiError, or nil if none found.
func (m *Lookup) ValidateAll() error {
	return m.validate(true)
}

func (m *Lookup) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Name

	if len(errors) > 0 {
		return LookupMultiError(errors)
	}

	return nil
}

// LookupMultiError is an error wrapping multiple validation errors returned by
// Lookup.ValidateAll() if the designated constraints aren't met.
type LookupMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m LookupMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m LookupMultiError) AllErrors() []error { return m }

// LookupValidationError is the validation error returned by Lookup.Validate if
// the designated constraints aren't met.
type LookupValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e LookupValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e LookupValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e LookupValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e LookupValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e LookupValidationError) ErrorName() string { return "LookupValidationError" }

// Error satisfies the builtin error interface
func (e LookupValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sLookup.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = LookupValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = LookupValidationError{}

// Validate checks the field values on Sorting with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Sorting) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Sorting with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in SortingMultiError, or nil if none found.
func (m *Sorting) ValidateAll() error {
	return m.validate(true)
}

func (m *Sorting) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if _, ok := OrderDirection_name[int32(m.GetOrderDirection())]; !ok {
		err := SortingValidationError{
			field:  "OrderDirection",
			reason: "value must be one of the defined enum values",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if _, ok := OrderBy_name[int32(m.GetOrderBy())]; !ok {
		err := SortingValidationError{
			field:  "OrderBy",
			reason: "value must be one of the defined enum values",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return SortingMultiError(errors)
	}

	return nil
}

// SortingMultiError is an error wrapping multiple validation errors returned
// by Sorting.ValidateAll() if the designated constraints aren't met.
type SortingMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SortingMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SortingMultiError) AllErrors() []error { return m }

// SortingValidationError is the validation error returned by Sorting.Validate
// if the designated constraints aren't met.
type SortingValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SortingValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SortingValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SortingValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SortingValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SortingValidationError) ErrorName() string { return "SortingValidationError" }

// Error satisfies the builtin error interface
func (e SortingValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSorting.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SortingValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SortingValidationError{}
