// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: message/employee.proto

package message

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on Employee with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Employee) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Employee with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in EmployeeMultiError, or nil
// if none found.
func (m *Employee) ValidateAll() error {
	return m.validate(true)
}

func (m *Employee) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for FullName

	if _, ok := EmployeePosition_name[int32(m.GetPosition())]; !ok {
		err := EmployeeValidationError{
			field:  "Position",
			reason: "value must be one of the defined enum values",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetCreatedBy()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, EmployeeValidationError{
					field:  "CreatedBy",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, EmployeeValidationError{
					field:  "CreatedBy",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCreatedBy()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return EmployeeValidationError{
				field:  "CreatedBy",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetCreatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, EmployeeValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, EmployeeValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCreatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return EmployeeValidationError{
				field:  "CreatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return EmployeeMultiError(errors)
	}

	return nil
}

// EmployeeMultiError is an error wrapping multiple validation errors returned
// by Employee.ValidateAll() if the designated constraints aren't met.
type EmployeeMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m EmployeeMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m EmployeeMultiError) AllErrors() []error { return m }

// EmployeeValidationError is the validation error returned by
// Employee.Validate if the designated constraints aren't met.
type EmployeeValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e EmployeeValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e EmployeeValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e EmployeeValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e EmployeeValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e EmployeeValidationError) ErrorName() string { return "EmployeeValidationError" }

// Error satisfies the builtin error interface
func (e EmployeeValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sEmployee.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = EmployeeValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = EmployeeValidationError{}

// Validate checks the field values on CreateEmployeeRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateEmployeeRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateEmployeeRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateEmployeeRequestMultiError, or nil if none found.
func (m *CreateEmployeeRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateEmployeeRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetFullName()) < 1 {
		err := CreateEmployeeRequestValidationError{
			field:  "FullName",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if _, ok := _CreateEmployeeRequest_Position_NotInLookup[m.GetPosition()]; ok {
		err := CreateEmployeeRequestValidationError{
			field:  "Position",
			reason: "value must not be in list [EMPLOYEE_POSITION_UNSPECIFIED]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if _, ok := EmployeePosition_name[int32(m.GetPosition())]; !ok {
		err := CreateEmployeeRequestValidationError{
			field:  "Position",
			reason: "value must be one of the defined enum values",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetCreatedById() <= 0 {
		err := CreateEmployeeRequestValidationError{
			field:  "CreatedById",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return CreateEmployeeRequestMultiError(errors)
	}

	return nil
}

// CreateEmployeeRequestMultiError is an error wrapping multiple validation
// errors returned by CreateEmployeeRequest.ValidateAll() if the designated
// constraints aren't met.
type CreateEmployeeRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateEmployeeRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateEmployeeRequestMultiError) AllErrors() []error { return m }

// CreateEmployeeRequestValidationError is the validation error returned by
// CreateEmployeeRequest.Validate if the designated constraints aren't met.
type CreateEmployeeRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateEmployeeRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateEmployeeRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateEmployeeRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateEmployeeRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateEmployeeRequestValidationError) ErrorName() string {
	return "CreateEmployeeRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CreateEmployeeRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateEmployeeRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateEmployeeRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateEmployeeRequestValidationError{}

var _CreateEmployeeRequest_Position_NotInLookup = map[EmployeePosition]struct{}{
	0: {},
}

// Validate checks the field values on UpdateEmployeeRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateEmployeeRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateEmployeeRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateEmployeeRequestMultiError, or nil if none found.
func (m *UpdateEmployeeRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateEmployeeRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetId() <= 0 {
		err := UpdateEmployeeRequestValidationError{
			field:  "Id",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.FullName != nil {
		// no validation rules for FullName
	}

	if m.Position != nil {

		if _, ok := EmployeePosition_name[int32(m.GetPosition())]; !ok {
			err := UpdateEmployeeRequestValidationError{
				field:  "Position",
				reason: "value must be one of the defined enum values",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	}

	if len(errors) > 0 {
		return UpdateEmployeeRequestMultiError(errors)
	}

	return nil
}

// UpdateEmployeeRequestMultiError is an error wrapping multiple validation
// errors returned by UpdateEmployeeRequest.ValidateAll() if the designated
// constraints aren't met.
type UpdateEmployeeRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateEmployeeRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateEmployeeRequestMultiError) AllErrors() []error { return m }

// UpdateEmployeeRequestValidationError is the validation error returned by
// UpdateEmployeeRequest.Validate if the designated constraints aren't met.
type UpdateEmployeeRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateEmployeeRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateEmployeeRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateEmployeeRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateEmployeeRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateEmployeeRequestValidationError) ErrorName() string {
	return "UpdateEmployeeRequestValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateEmployeeRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateEmployeeRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateEmployeeRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateEmployeeRequestValidationError{}

// Validate checks the field values on SearchEmployeesResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *SearchEmployeesResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SearchEmployeesResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SearchEmployeesResponseMultiError, or nil if none found.
func (m *SearchEmployeesResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *SearchEmployeesResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetItems() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, SearchEmployeesResponseValidationError{
						field:  fmt.Sprintf("Items[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, SearchEmployeesResponseValidationError{
						field:  fmt.Sprintf("Items[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return SearchEmployeesResponseValidationError{
					field:  fmt.Sprintf("Items[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return SearchEmployeesResponseMultiError(errors)
	}

	return nil
}

// SearchEmployeesResponseMultiError is an error wrapping multiple validation
// errors returned by SearchEmployeesResponse.ValidateAll() if the designated
// constraints aren't met.
type SearchEmployeesResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SearchEmployeesResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SearchEmployeesResponseMultiError) AllErrors() []error { return m }

// SearchEmployeesResponseValidationError is the validation error returned by
// SearchEmployeesResponse.Validate if the designated constraints aren't met.
type SearchEmployeesResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SearchEmployeesResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SearchEmployeesResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SearchEmployeesResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SearchEmployeesResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SearchEmployeesResponseValidationError) ErrorName() string {
	return "SearchEmployeesResponseValidationError"
}

// Error satisfies the builtin error interface
func (e SearchEmployeesResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSearchEmployeesResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SearchEmployeesResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SearchEmployeesResponseValidationError{}
