// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.0
// source: message/employee.proto

package message

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Employee struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FullName      string                 `protobuf:"bytes,2,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	Position      EmployeePosition       `protobuf:"varint,3,opt,name=position,proto3,enum=guard.v1.EmployeePosition" json:"position,omitempty"`
	CreatedBy     *Lookup                `protobuf:"bytes,4,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Employee) Reset() {
	*x = Employee{}
	mi := &file_message_employee_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Employee) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Employee) ProtoMessage() {}

func (x *Employee) ProtoReflect() protoreflect.Message {
	mi := &file_message_employee_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Employee.ProtoReflect.Descriptor instead.
func (*Employee) Descriptor() ([]byte, []int) {
	return file_message_employee_proto_rawDescGZIP(), []int{0}
}

func (x *Employee) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Employee) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *Employee) GetPosition() EmployeePosition {
	if x != nil {
		return x.Position
	}
	return EmployeePosition_EMPLOYEE_POSITION_UNSPECIFIED
}

func (x *Employee) GetCreatedBy() *Lookup {
	if x != nil {
		return x.CreatedBy
	}
	return nil
}

func (x *Employee) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type CreateEmployeeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FullName      string                 `protobuf:"bytes,1,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	Position      EmployeePosition       `protobuf:"varint,2,opt,name=position,proto3,enum=guard.v1.EmployeePosition" json:"position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEmployeeRequest) Reset() {
	*x = CreateEmployeeRequest{}
	mi := &file_message_employee_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEmployeeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEmployeeRequest) ProtoMessage() {}

func (x *CreateEmployeeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_employee_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEmployeeRequest.ProtoReflect.Descriptor instead.
func (*CreateEmployeeRequest) Descriptor() ([]byte, []int) {
	return file_message_employee_proto_rawDescGZIP(), []int{1}
}

func (x *CreateEmployeeRequest) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *CreateEmployeeRequest) GetPosition() EmployeePosition {
	if x != nil {
		return x.Position
	}
	return EmployeePosition_EMPLOYEE_POSITION_UNSPECIFIED
}

type UpdateEmployeeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FullName      *string                `protobuf:"bytes,2,opt,name=full_name,json=fullName,proto3,oneof" json:"full_name,omitempty"`
	Position      *EmployeePosition      `protobuf:"varint,3,opt,name=position,proto3,enum=guard.v1.EmployeePosition,oneof" json:"position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEmployeeRequest) Reset() {
	*x = UpdateEmployeeRequest{}
	mi := &file_message_employee_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEmployeeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEmployeeRequest) ProtoMessage() {}

func (x *UpdateEmployeeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_employee_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEmployeeRequest.ProtoReflect.Descriptor instead.
func (*UpdateEmployeeRequest) Descriptor() ([]byte, []int) {
	return file_message_employee_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateEmployeeRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateEmployeeRequest) GetFullName() string {
	if x != nil && x.FullName != nil {
		return *x.FullName
	}
	return ""
}

func (x *UpdateEmployeeRequest) GetPosition() EmployeePosition {
	if x != nil && x.Position != nil {
		return *x.Position
	}
	return EmployeePosition_EMPLOYEE_POSITION_UNSPECIFIED
}

type SearchEmployeesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Employee            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchEmployeesResponse) Reset() {
	*x = SearchEmployeesResponse{}
	mi := &file_message_employee_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchEmployeesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchEmployeesResponse) ProtoMessage() {}

func (x *SearchEmployeesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_message_employee_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchEmployeesResponse.ProtoReflect.Descriptor instead.
func (*SearchEmployeesResponse) Descriptor() ([]byte, []int) {
	return file_message_employee_proto_rawDescGZIP(), []int{3}
}

func (x *SearchEmployeesResponse) GetItems() []*Employee {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_message_employee_proto protoreflect.FileDescriptor

const file_message_employee_proto_rawDesc = "" +
	"\n" +
	"\x16message/employee.proto\x12\bguard.v1\x1a\x1fgoogle/api/field_behavior.proto\x1a\x17validate/validate.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x14message/common.proto\"\xe5\x01\n" +
	"\bEmployee\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tfull_name\x18\x02 \x01(\tR\bfullName\x12@\n" +
	"\bposition\x18\x03 \x01(\x0e2\x1a.guard.v1.EmployeePositionB\b\xfaB\x05\x82\x01\x02\x10\x01R\bposition\x12/\n" +
	"\n" +
	"created_by\x18\x04 \x01(\v2\x10.guard.v1.LookupR\tcreatedBy\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x87\x01\n" +
	"\x15CreateEmployeeRequest\x12'\n" +
	"\tfull_name\x18\x01 \x01(\tB\n" +
	"\xe0A\x02\xfaB\x04r\x02\x10\x01R\bfullName\x12E\n" +
	"\bposition\x18\x02 \x01(\x0e2\x1a.guard.v1.EmployeePositionB\r\xe0A\x02\xfaB\a\x82\x01\x04\x10\x01 \x00R\bposition\"\xb7\x01\n" +
	"\x15UpdateEmployeeRequest\x12\x1a\n" +
	"\x02id\x18\x01 \x01(\x03B\n" +
	"\xe0A\x02\xfaB\x04\"\x02 \x00R\x02id\x12 \n" +
	"\tfull_name\x18\x02 \x01(\tH\x00R\bfullName\x88\x01\x01\x12E\n" +
	"\bposition\x18\x03 \x01(\x0e2\x1a.guard.v1.EmployeePositionB\b\xfaB\x05\x82\x01\x02\x10\x01H\x01R\bposition\x88\x01\x01B\f\n" +
	"\n" +
	"_full_nameB\v\n" +
	"\t_position\"C\n" +
	"\x17SearchEmployeesResponse\x12(\n" +
	"\x05items\x18\x01 \x03(\v2\x12.guard.v1.EmployeeR\x05itemsB=Z;github.com/gigasigmaslav/guard-panel-api/pkg/api/v1/messageb\x06proto3"

var (
	file_message_employee_proto_rawDescOnce sync.Once
	file_message_employee_proto_rawDescData []byte
)

func file_message_employee_proto_rawDescGZIP() []byte {
	file_message_employee_proto_rawDescOnce.Do(func() {
		file_message_employee_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_message_employee_proto_rawDesc), len(file_message_employee_proto_rawDesc)))
	})
	return file_message_employee_proto_rawDescData
}

var file_message_employee_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_message_employee_proto_goTypes = []any{
	(*Employee)(nil),                // 0: guard.v1.Employee
	(*CreateEmployeeRequest)(nil),   // 1: guard.v1.CreateEmployeeRequest
	(*UpdateEmployeeRequest)(nil),   // 2: guard.v1.UpdateEmployeeRequest
	(*SearchEmployeesResponse)(nil), // 3: guard.v1.SearchEmployeesResponse
	(EmployeePosition)(0),           // 4: guard.v1.EmployeePosition
	(*Lookup)(nil),                  // 5: guard.v1.Lookup
	(*timestamppb.Timestamp)(nil),   // 6: google.protobuf.Timestamp
}
var file_message_employee_proto_depIdxs = []int32{
	4, // 0: guard.v1.Employee.position:type_name -> guard.v1.EmployeePosition
	5, // 1: guard.v1.Employee.created_by:type_name -> guard.v1.Lookup
	6, // 2: guard.v1.Employee.created_at:type_name -> google.protobuf.Timestamp
	4, // 3: guard.v1.CreateEmployeeRequest.position:type_name -> guard.v1.EmployeePosition
	4, // 4: guard.v1.UpdateEmployeeRequest.position:type_name -> guard.v1.EmployeePosition
	0, // 5: guard.v1.SearchEmployeesResponse.items:type_name -> guard.v1.Employee
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_message_employee_proto_init() }
func file_message_employee_proto_init() {
	if File_message_employee_proto != nil {
		return
	}
	file_message_common_proto_init()
	file_message_employee_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_message_employee_proto_rawDesc), len(file_message_employee_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_message_employee_proto_goTypes,
		DependencyIndexes: file_message_employee_proto_depIdxs,
		MessageInfos:      file_message_employee_proto_msgTypes,
	}.Build()
	File_message_employee_proto = out.File
	file_message_employee_proto_goTypes = nil
	file_message_employee_proto_depIdxs = nil
}
