// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.0
// source: message/office.proto

package message

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Office struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	CreatedBy     *Lookup                `protobuf:"bytes,4,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Office) Reset() {
	*x = Office{}
	mi := &file_message_office_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Office) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Office) ProtoMessage() {}

func (x *Office) ProtoReflect() protoreflect.Message {
	mi := &file_message_office_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Office.ProtoReflect.Descriptor instead.
func (*Office) Descriptor() ([]byte, []int) {
	return file_message_office_proto_rawDescGZIP(), []int{0}
}

func (x *Office) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Office) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Office) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Office) GetCreatedBy() *Lookup {
	if x != nil {
		return x.CreatedBy
	}
	return nil
}

func (x *Office) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type CreateOfficeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOfficeRequest) Reset() {
	*x = CreateOfficeRequest{}
	mi := &file_message_office_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOfficeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOfficeRequest) ProtoMessage() {}

func (x *CreateOfficeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_office_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOfficeRequest.ProtoReflect.Descriptor instead.
func (*CreateOfficeRequest) Descriptor() ([]byte, []int) {
	return file_message_office_proto_rawDescGZIP(), []int{1}
}

func (x *CreateOfficeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateOfficeRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type UpdateOfficeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Address       *string                `protobuf:"bytes,3,opt,name=address,proto3,oneof" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOfficeRequest) Reset() {
	*x = UpdateOfficeRequest{}
	mi := &file_message_office_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOfficeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOfficeRequest) ProtoMessage() {}

func (x *UpdateOfficeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_office_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOfficeRequest.ProtoReflect.Descriptor instead.
func (*UpdateOfficeRequest) Descriptor() ([]byte, []int) {
	return file_message_office_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateOfficeRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateOfficeRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateOfficeRequest) GetAddress() string {
	if x != nil && x.Address != nil {
		return *x.Address
	}
	return ""
}

type SearchOfficesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Office              `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchOfficesResponse) Reset() {
	*x = SearchOfficesResponse{}
	mi := &file_message_office_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchOfficesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchOfficesResponse) ProtoMessage() {}

func (x *SearchOfficesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_message_office_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchOfficesResponse.ProtoReflect.Descriptor instead.
func (*SearchOfficesResponse) Descriptor() ([]byte, []int) {
	return file_message_office_proto_rawDescGZIP(), []int{3}
}

func (x *SearchOfficesResponse) GetItems() []*Office {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_message_office_proto protoreflect.FileDescriptor

const file_message_office_proto_rawDesc = "" +
	"\n" +
	"\x14message/office.proto\x12\bguard.v1\x1a\x1fgoogle/api/field_behavior.proto\x1a\x17validate/validate.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x14message/common.proto\"\xb2\x01\n" +
	"\x06Office\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x12/\n" +
	"\n" +
	"created_by\x18\x04 \x01(\v2\x10.guard.v1.LookupR\tcreatedBy\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"[\n" +
	"\x13CreateOfficeRequest\x12\x1e\n" +
	"\x04name\x18\x01 \x01(\tB\n" +
	"\xe0A\x02\xfaB\x04r\x02\x10\x01R\x04name\x12$\n" +
	"\aaddress\x18\x02 \x01(\tB\n" +
	"\xe0A\x02\xfaB\x04r\x02\x10\x01R\aaddress\"~\n" +
	"\x13UpdateOfficeRequest\x12\x1a\n" +
	"\x02id\x18\x01 \x01(\x03B\n" +
	"\xe0A\x02\xfaB\x04\"\x02 \x00R\x02id\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01\x12\x1d\n" +
	"\aaddress\x18\x03 \x01(\tH\x01R\aaddress\x88\x01\x01B\a\n" +
	"\x05_nameB\n" +
	"\n" +
	"\b_address\"?\n" +
	"\x15SearchOfficesResponse\x12&\n" +
	"\x05items\x18\x01 \x03(\v2\x10.guard.v1.OfficeR\x05itemsB=Z;github.com/gigasigmaslav/guard-panel-api/pkg/api/v1/messageb\x06proto3"

var (
	file_message_office_proto_rawDescOnce sync.Once
	file_message_office_proto_rawDescData []byte
)

func file_message_office_proto_rawDescGZIP() []byte {
	file_message_office_proto_rawDescOnce.Do(func() {
		file_message_office_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_message_office_proto_rawDesc), len(file_message_office_proto_rawDesc)))
	})
	return file_message_office_proto_rawDescData
}

var file_message_office_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_message_office_proto_goTypes = []any{
	(*Office)(nil),                // 0: guard.v1.Office
	(*CreateOfficeRequest)(nil),   // 1: guard.v1.CreateOfficeRequest
	(*UpdateOfficeRequest)(nil),   // 2: guard.v1.UpdateOfficeRequest
	(*SearchOfficesResponse)(nil), // 3: guard.v1.SearchOfficesResponse
	(*Lookup)(nil),                // 4: guard.v1.Lookup
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_message_office_proto_depIdxs = []int32{
	4, // 0: guard.v1.Office.created_by:type_name -> guard.v1.Lookup
	5, // 1: guard.v1.Office.created_at:type_name -> google.protobuf.Timestamp
	0, // 2: guard.v1.SearchOfficesResponse.items:type_name -> guard.v1.Office
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_message_office_proto_init() }
func file_message_office_proto_init() {
	if File_message_office_proto != nil {
		return
	}
	file_message_common_proto_init()
	file_message_office_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_message_office_proto_rawDesc), len(file_message_office_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_message_office_proto_goTypes,
		DependencyIndexes: file_message_office_proto_depIdxs,
		MessageInfos:      file_message_office_proto_msgTypes,
	}.Build()
	File_message_office_proto = out.File
	file_message_office_proto_goTypes = nil
	file_message_office_proto_depIdxs = nil
}
