// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: message/office.proto

package message

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on Office with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Office) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Office with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in OfficeMultiError, or nil if none found.
func (m *Office) ValidateAll() error {
	return m.validate(true)
}

func (m *Office) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Name

	// no validation rules for Address

	if all {
		switch v := interface{}(m.GetCreatedBy()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, OfficeValidationError{
					field:  "CreatedBy",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, OfficeValidationError{
					field:  "CreatedBy",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCreatedBy()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return OfficeValidationError{
				field:  "CreatedBy",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetCreatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, OfficeValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, OfficeValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCreatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return OfficeValidationError{
				field:  "CreatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return OfficeMultiError(errors)
	}

	return nil
}

// OfficeMultiError is an error wrapping multiple validation errors returned by
// Office.ValidateAll() if the designated constraints aren't met.
type OfficeMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m OfficeMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m OfficeMultiError) AllErrors() []error { return m }

// OfficeValidationError is the validation error returned by Office.Validate if
// the designated constraints aren't met.
type OfficeValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e OfficeValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e OfficeValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e OfficeValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e OfficeValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e OfficeValidationError) ErrorName() string { return "OfficeValidationError" }

// Error satisfies the builtin error interface
func (e OfficeValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sOffice.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = OfficeValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = OfficeValidationError{}

// Validate checks the field values on CreateOfficeRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateOfficeRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateOfficeRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateOfficeRequestMultiError, or nil if none found.
func (m *CreateOfficeRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateOfficeRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetName()) < 1 {
		err := CreateOfficeRequestValidationError{
			field:  "Name",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetAddress()) < 1 {
		err := CreateOfficeRequestValidationError{
			field:  "Address",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetCreatedById() <= 0 {
		err := CreateOfficeRequestValidationError{
			field:  "CreatedById",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return CreateOfficeRequestMultiError(errors)
	}

	return nil
}

// CreateOfficeRequestMultiError is an error wrapping multiple validation
// errors returned by CreateOfficeRequest.ValidateAll() if the designated
// constraints aren't met.
type CreateOfficeRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateOfficeRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateOfficeRequestMultiError) AllErrors() []error { return m }

// CreateOfficeRequestValidationError is the validation error returned by
// CreateOfficeRequest.Validate if the designated constraints aren't met.
type CreateOfficeRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateOfficeRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateOfficeRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateOfficeRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateOfficeRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateOfficeRequestValidationError) ErrorName() string {
	return "CreateOfficeRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CreateOfficeRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateOfficeRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateOfficeRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateOfficeRequestValidationError{}

// Validate checks the field values on UpdateOfficeRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateOfficeRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateOfficeRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateOfficeRequestMultiError, or nil if none found.
func (m *UpdateOfficeRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateOfficeRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetId() <= 0 {
		err := UpdateOfficeRequestValidationError{
			field:  "Id",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.Name != nil {
		// no validation rules for Name
	}

	if m.Address != nil {
		// no validation rules for Address
	}

	if len(errors) > 0 {
		return UpdateOfficeRequestMultiError(errors)
	}

	return nil
}

// UpdateOfficeRequestMultiError is an error wrapping multiple validation
// errors returned by UpdateOfficeRequest.ValidateAll() if the designated
// constraints aren't met.
type UpdateOfficeRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateOfficeRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateOfficeRequestMultiError) AllErrors() []error { return m }

// UpdateOfficeRequestValidationError is the validation error returned by
// UpdateOfficeRequest.Validate if the designated constraints aren't met.
type UpdateOfficeRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateOfficeRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateOfficeRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateOfficeRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateOfficeRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateOfficeRequestValidationError) ErrorName() string {
	return "UpdateOfficeRequestValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateOfficeRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateOfficeRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateOfficeRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateOfficeRequestValidationError{}

// Validate checks the field values on SearchOfficesResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *SearchOfficesResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SearchOfficesResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SearchOfficesResponseMultiError, or nil if none found.
func (m *SearchOfficesResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *SearchOfficesResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetItems() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, SearchOfficesResponseValidationError{
						field:  fmt.Sprintf("Items[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, SearchOfficesResponseValidationError{
						field:  fmt.Sprintf("Items[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return SearchOfficesResponseValidationError{
					field:  fmt.Sprintf("Items[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return SearchOfficesResponseMultiError(errors)
	}

	return nil
}

// SearchOfficesResponseMultiError is an error wrapping multiple validation
// errors returned by SearchOfficesResponse.ValidateAll() if the designated
// constraints aren't met.
type SearchOfficesResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SearchOfficesResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SearchOfficesResponseMultiError) AllErrors() []error { return m }

// SearchOfficesResponseValidationError is the validation error returned by
// SearchOfficesResponse.Validate if the designated constraints aren't met.
type SearchOfficesResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SearchOfficesResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SearchOfficesResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SearchOfficesResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SearchOfficesResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SearchOfficesResponseValidationError) ErrorName() string {
	return "SearchOfficesResponseValidationError"
}

// Error satisfies the builtin error interface
func (e SearchOfficesResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSearchOfficesResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SearchOfficesResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SearchOfficesResponseValidationError{}
