// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: message/refund.proto

package message

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on Refund with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Refund) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Refund with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in RefundMultiError, or nil if none found.
func (m *Refund) ValidateAll() error {
	return m.validate(true)
}

func (m *Refund) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for TaskId

	// no validation rules for Amount

	// no validation rules for Comment

	if all {
		switch v := interface{}(m.GetCreatedBy()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, RefundValidationError{
					field:  "CreatedBy",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, RefundValidationError{
					field:  "CreatedBy",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCreatedBy()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return RefundValidationError{
				field:  "CreatedBy",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetCreatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, RefundValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, RefundValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCreatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return RefundValidationError{
				field:  "CreatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return RefundMultiError(errors)
	}

	return nil
}

// RefundMultiError is an error wrapping multiple validation errors returned by
// Refund.ValidateAll() if the designated constraints aren't met.
type RefundMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RefundMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RefundMultiError) AllErrors() []error { return m }

// RefundValidationError is the validation error returned by Refund.Validate if
// the designated constraints aren't met.
type RefundValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RefundValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RefundValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RefundValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RefundValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RefundValidationError) ErrorName() string { return "RefundValidationError" }

// Error satisfies the builtin error interface
func (e RefundValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRefund.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RefundValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RefundValidationError{}

// Validate checks the field values on CreateRefundRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateRefundRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateRefundRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateRefundRequestMultiError, or nil if none found.
func (m *CreateRefundRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateRefundRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetTaskId() <= 0 {
		err := CreateRefundRequestValidationError{
			field:  "TaskId",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetAmount() <= 0 {
		err := CreateRefundRequestValidationError{
			field:  "Amount",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetComment()) < 1 {
		err := CreateRefundRequestValidationError{
			field:  "Comment",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetCreatedById() <= 0 {
		err := CreateRefundRequestValidationError{
			field:  "CreatedById",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return CreateRefundRequestMultiError(errors)
	}

	return nil
}

// CreateRefundRequestMultiError is an error wrapping multiple validation
// errors returned by CreateRefundRequest.ValidateAll() if the designated
// constraints aren't met.
type CreateRefundRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateRefundRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateRefundRequestMultiError) AllErrors() []error { return m }

// CreateRefundRequestValidationError is the validation error returned by
// CreateRefundRequest.Validate if the designated constraints aren't met.
type CreateRefundRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateRefundRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateRefundRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateRefundRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateRefundRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateRefundRequestValidationError) ErrorName() string {
	return "CreateRefundRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CreateRefundRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateRefundRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateRefundRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateRefundRequestValidationError{}
