// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.0
// source: message/task.proto

package message

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Task_TaskHistoryChange_TaskHistoryChangeEvent int32

const (
	Task_TaskHistoryChange_TASK_HISTORY_CHANGE_EVENT_UNSPECIFIED        Task_TaskHistoryChange_TaskHistoryChangeEvent = 0
	Task_TaskHistoryChange_TASK_HISTORY_CHANGE_EVENT_COMMENT_ADDED      Task_TaskHistoryChange_TaskHistoryChangeEvent = 1
	Task_TaskHistoryChange_TASK_HISTORY_CHANGE_EVENT_REFUND_ADDED       Task_TaskHistoryChange_TaskHistoryChangeEvent = 2
	Task_TaskHistoryChange_TASK_HISTORY_CHANGE_EVENT_VUD_DECISION_ADDED Task_TaskHistoryChange_TaskHistoryChangeEvent = 3
)

// Enum value maps for Task_TaskHistoryChange_TaskHistoryChangeEvent.
var (
	Task_TaskHistoryChange_TaskHistoryChangeEvent_name = map[int32]string{
		0: "TASK_HISTORY_CHANGE_EVENT_UNSPECIFIED",
		1: "TASK_HISTORY_CHANGE_EVENT_COMMENT_ADDED",
		2: "TASK_HISTORY_CHANGE_EVENT_REFUND_ADDED",
		3: "TASK_HISTORY_CHANGE_EVENT_VUD_DECISION_ADDED",
	}
	Task_TaskHistoryChange_TaskHistoryChangeEvent_value = map[string]int32{
		"TASK_HISTORY_CHANGE_EVENT_UNSPECIFIED":        0,
		"TASK_HISTORY_CHANGE_EVENT_COMMENT_ADDED":      1,
		"TASK_HISTORY_CHANGE_EVENT_REFUND_ADDED":       2,
		"TASK_HISTORY_CHANGE_EVENT_VUD_DECISION_ADDED": 3,
	}
)

func (x Task_TaskHistoryChange_TaskHistoryChangeEvent) Enum() *Task_TaskHistoryChange_TaskHistoryChangeEvent {
	p := new(Task_TaskHistoryChange_TaskHistoryChangeEvent)
	*p = x
	return p
}

func (x Task_TaskHistoryChange_TaskHistoryChangeEvent) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Task_TaskHistoryChange_TaskHistoryChangeEvent) Descriptor() protoreflect.EnumDescriptor {
	return file_message_task_proto_enumTypes[0].Descriptor()
}

func (Task_TaskHistoryChange_TaskHistoryChangeEvent) Type() protoreflect.EnumType {
	return &file_message_task_proto_enumTypes[0]
}

func (x Task_TaskHistoryChange_TaskHistoryChangeEvent) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Task_TaskHistoryChange_TaskHistoryChangeEvent.Descriptor instead.
func (Task_TaskHistoryChange_TaskHistoryChangeEvent) EnumDescriptor() ([]byte, []int) {
	return file_message_task_proto_rawDescGZIP(), []int{1, 3, 0}
}

type CreateTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DamageAmount  int64                  `protobuf:"varint,1,opt,name=damage_amount,json=damageAmount,proto3" json:"damage_amount,omitempty"`
	Priority      TaskPriority           `protobuf:"varint,2,opt,name=priority,proto3,enum=guard.v1.TaskPriority" json:"priority,omitempty"`
	ExecutorId    int64                  `protobuf:"varint,3,opt,name=executor_id,json=executorId,proto3" json:"executor_id,omitempty"`
	CreatedById   int64                  `protobuf:"varint,4,opt,name=created_by_id,json=createdById,proto3" json:"created_by_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTaskRequest) Reset() {
	*x = CreateTaskRequest{}
	mi := &file_message_task_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskRequest) ProtoMessage() {}

func (x *CreateTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_task_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskRequest.ProtoReflect.Descriptor instead.
func (*CreateTaskRequest) Descriptor() ([]byte, []int) {
	return file_message_task_proto_rawDescGZIP(), []int{0}
}

func (x *CreateTaskRequest) GetDamageAmount() int64 {
	if x != nil {
		return x.DamageAmount
	}
	return 0
}

func (x *CreateTaskRequest) GetPriority() TaskPriority {
	if x != nil {
		return x.Priority
	}
	return TaskPriority_TASK_PRIORITY_UNSPECIFIED
}

func (x *CreateTaskRequest) GetExecutorId() int64 {
	if x != nil {
		return x.ExecutorId
	}
	return 0
}

func (x *CreateTaskRequest) GetCreatedById() int64 {
	if x != nil {
		return x.CreatedById
	}
	return 0
}

type Task struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Id           int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DamageAmount int64                  `protobuf:"varint,2,opt,name=damage_amount,json=damageAmount,proto3" json:"damage_amount,omitempty"`
	Priority     TaskPriority           `protobuf:"varint,3,opt,name=priority,proto3,enum=guard.v1.TaskPriority" json:"priority,omitempty"`
	Status       TaskStatus             `protobuf:"varint,4,opt,name=status,proto3,enum=guard.v1.TaskStatus" json:"status,omitempty"`
	Executor     *Lookup                `protobuf:"bytes,5,opt,name=executor,proto3" json:"executor,omitempty"`
	Violator     *Lookup                `protobuf:"bytes,6,opt,name=violator,proto3" json:"violator,omitempty"`
	Office       *Lookup                `protobuf:"bytes,7,opt,name=office,proto3" json:"office,omitempty"`
	CreatedBy    *Lookup                `protobuf:"bytes,8,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	CreatedAt    *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	StartDate    *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate      *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=end_date,json=endDate,proto3,oneof" json:"end_date,omitempty"`
	// aggregate parts
	Refunds        *Task_TaskRefund          `protobuf:"bytes,12,opt,name=refunds,proto3" json:"refunds,omitempty"`
	VudDecisions   *Task_TaskVudDecision     `protobuf:"bytes,13,opt,name=vud_decisions,json=vudDecisions,proto3" json:"vud_decisions,omitempty"`
	Comments       []*Task_TaskComment       `protobuf:"bytes,14,rep,name=comments,proto3" json:"comments,omitempty"`
	HistoryChanges []*Task_TaskHistoryChange `protobuf:"bytes,15,rep,name=history_changes,json=historyChanges,proto3" json:"history_changes,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_message_task_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_message_task_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_message_task_proto_rawDescGZIP(), []int{1}
}

func (x *Task) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Task) GetDamageAmount() int64 {
	if x != nil {
		return x.DamageAmount
	}
	return 0
}

func (x *Task) GetPriority() TaskPriority {
	if x != nil {
		return x.Priority
	}
	return TaskPriority_TASK_PRIORITY_UNSPECIFIED
}

func (x *Task) GetStatus() TaskStatus {
	if x != nil {
		return x.Status
	}
	return TaskStatus_CASE_STATUS_UNSPECIFIED
}

func (x *Task) GetExecutor() *Lookup {
	if x != nil {
		return x.Executor
	}
	return nil
}

func (x *Task) GetViolator() *Lookup {
	if x != nil {
		return x.Violator
	}
	return nil
}

func (x *Task) GetOffice() *Lookup {
	if x != nil {
		return x.Office
	}
	return nil
}

func (x *Task) GetCreatedBy() *Lookup {
	if x != nil {
		return x.CreatedBy
	}
	return nil
}

func (x *Task) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Task) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *Task) GetEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

func (x *Task) GetRefunds() *Task_TaskRefund {
	if x != nil {
		return x.Refunds
	}
	return nil
}

func (x *Task) GetVudDecisions() *Task_TaskVudDecision {
	if x != nil {
		return x.VudDecisions
	}
	return nil
}

func (x *Task) GetComments() []*Task_TaskComment {
	if x != nil {
		return x.Comments
	}
	return nil
}

func (x *Task) GetHistoryChanges() []*Task_TaskHistoryChange {
	if x != nil {
		return x.HistoryChanges
	}
	return nil
}

type GetTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *Task                  `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskResponse) Reset() {
	*x = GetTaskResponse{}
	mi := &file_message_task_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskResponse) ProtoMessage() {}

func (x *GetTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_message_task_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskResponse.ProtoReflect.Descriptor instead.
func (*GetTaskResponse) Descriptor() ([]byte, []int) {
	return file_message_task_proto_rawDescGZIP(), []int{2}
}

func (x *GetTaskResponse) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

type UpdateTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DamageAmount  *int64                 `protobuf:"varint,2,opt,name=damage_amount,json=damageAmount,proto3,oneof" json:"damage_amount,omitempty"`
	Priority      *TaskPriority          `protobuf:"varint,3,opt,name=priority,proto3,enum=guard.v1.TaskPriority,oneof" json:"priority,omitempty"`
	Status        *TaskStatus            `protobuf:"varint,4,opt,name=status,proto3,enum=guard.v1.TaskStatus,oneof" json:"status,omitempty"`
	EndDate       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=end_date,json=endDate,proto3,oneof" json:"end_date,omitempty"`
	ExecutorId    *int64                 `protobuf:"varint,6,opt,name=executor_id,json=executorId,proto3,oneof" json:"executor_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTaskRequest) Reset() {
	*x = UpdateTaskRequest{}
	mi := &file_message_task_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTaskRequest) ProtoMessage() {}

func (x *UpdateTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_task_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTaskRequest.ProtoReflect.Descriptor instead.
func (*UpdateTaskRequest) Descriptor() ([]byte, []int) {
	return file_message_task_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateTaskRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateTaskRequest) GetDamageAmount() int64 {
	if x != nil && x.DamageAmount != nil {
		return *x.DamageAmount
	}
	return 0
}

func (x *UpdateTaskRequest) GetPriority() TaskPriority {
	if x != nil && x.Priority != nil {
		return *x.Priority
	}
	return TaskPriority_TASK_PRIORITY_UNSPECIFIED
}

func (x *UpdateTaskRequest) GetStatus() TaskStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return TaskStatus_CASE_STATUS_UNSPECIFIED
}

func (x *UpdateTaskRequest) GetEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

func (x *UpdateTaskRequest) GetExecutorId() int64 {
	if x != nil && x.ExecutorId != nil {
		return *x.ExecutorId
	}
	return 0
}

type SearchTasksRequest struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Page          int32                      `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PerPage       int32                      `protobuf:"varint,2,opt,name=per_page,json=perPage,proto3" json:"per_page,omitempty"`
	Sorting       *Sorting                   `protobuf:"bytes,3,opt,name=sorting,proto3" json:"sorting,omitempty"`
	Status        TaskStatus                 `protobuf:"varint,4,opt,name=status,proto3,enum=guard.v1.TaskStatus" json:"status,omitempty"`
	Filter        *SearchTasksRequest_Filter `protobuf:"bytes,5,opt,name=filter,proto3,oneof" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchTasksRequest) Reset() {
	*x = SearchTasksRequest{}
	mi := &file_message_task_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchTasksRequest) ProtoMessage() {}

func (x *SearchTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_task_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchTasksRequest.ProtoReflect.Descriptor instead.
func (*SearchTasksRequest) Descriptor() ([]byte, []int) {
	return file_message_task_proto_rawDescGZIP(), []int{4}
}

func (x *SearchTasksRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchTasksRequest) GetPerPage() int32 {
	if x != nil {
		return x.PerPage
	}
	return 0
}

func (x *SearchTasksRequest) GetSorting() *Sorting {
	if x != nil {
		return x.Sorting
	}
	return nil
}

func (x *SearchTasksRequest) GetStatus() TaskStatus {
	if x != nil {
		return x.Status
	}
	return TaskStatus_CASE_STATUS_UNSPECIFIED
}

func (x *SearchTasksRequest) GetFilter() *SearchTasksRequest_Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

type SearchTasksResponse struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	Items         []*SearchTasksResponse_TaskLookup `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Total         int64                             `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchTasksResponse) Reset() {
	*x = SearchTasksResponse{}
	mi := &file_message_task_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchTasksResponse) ProtoMessage() {}

func (x *SearchTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_message_task_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchTasksResponse.ProtoReflect.Descriptor instead.
func (*SearchTasksResponse) Descriptor() ([]byte, []int) {
	return file_message_task_proto_rawDescGZIP(), []int{5}
}

func (x *SearchTasksResponse) GetItems() []*SearchTasksResponse_TaskLookup {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *SearchTasksResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type Task_TaskRefund struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Amount        int64                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Comment       *string                `protobuf:"bytes,3,opt,name=comment,proto3,oneof" json:"comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task_TaskRefund) Reset() {
	*x = Task_TaskRefund{}
	mi := &file_message_task_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task_TaskRefund) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task_TaskRefund) ProtoMessage() {}

func (x *Task_TaskRefund) ProtoReflect() protoreflect.Message {
	mi := &file_message_task_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task_TaskRefund.ProtoReflect.Descriptor instead.
func (*Task_TaskRefund) Descriptor() ([]byte, []int) {
	return file_message_task_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Task_TaskRefund) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Task_TaskRefund) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Task_TaskRefund) GetComment() string {
	if x != nil && x.Comment != nil {
		return *x.Comment
	}
	return ""
}

type Task_TaskVudDecision struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Kusp               string                 `protobuf:"bytes,2,opt,name=kusp,proto3" json:"kusp,omitempty"`
	Ud                 *string                `protobuf:"bytes,3,opt,name=ud,proto3,oneof" json:"ud,omitempty"`
	CriminalCaseOpened *bool                  `protobuf:"varint,4,opt,name=criminal_case_opened,json=criminalCaseOpened,proto3,oneof" json:"criminal_case_opened,omitempty"`
	Comment            *string                `protobuf:"bytes,5,opt,name=comment,proto3,oneof" json:"comment,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Task_TaskVudDecision) Reset() {
	*x = Task_TaskVudDecision{}
	mi := &file_message_task_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task_TaskVudDecision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task_TaskVudDecision) ProtoMessage() {}

func (x *Task_TaskVudDecision) ProtoReflect() protoreflect.Message {
	mi := &file_message_task_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task_TaskVudDecision.ProtoReflect.Descriptor instead.
func (*Task_TaskVudDecision) Descriptor() ([]byte, []int) {
	return file_message_task_proto_rawDescGZIP(), []int{1, 1}
}

func (x *Task_TaskVudDecision) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Task_TaskVudDecision) GetKusp() string {
	if x != nil {
		return x.Kusp
	}
	return ""
}

func (x *Task_TaskVudDecision) GetUd() string {
	if x != nil && x.Ud != nil {
		return *x.Ud
	}
	return ""
}

func (x *Task_TaskVudDecision) GetCriminalCaseOpened() bool {
	if x != nil && x.CriminalCaseOpened != nil {
		return *x.CriminalCaseOpened
	}
	return false
}

func (x *Task_TaskVudDecision) GetComment() string {
	if x != nil && x.Comment != nil {
		return *x.Comment
	}
	return ""
}

type Task_TaskComment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Comment       string                 `protobuf:"bytes,2,opt,name=comment,proto3" json:"comment,omitempty"`
	CreatedBy     *Lookup                `protobuf:"bytes,3,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task_TaskComment) Reset() {
	*x = Task_TaskComment{}
	mi := &file_message_task_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task_TaskComment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task_TaskComment) ProtoMessage() {}

func (x *Task_TaskComment) ProtoReflect() protoreflect.Message {
	mi := &file_message_task_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task_TaskComment.ProtoReflect.Descriptor instead.
func (*Task_TaskComment) Descriptor() ([]byte, []int) {
	return file_message_task_proto_rawDescGZIP(), []int{1, 2}
}

func (x *Task_TaskComment) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Task_TaskComment) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *Task_TaskComment) GetCreatedBy() *Lookup {
	if x != nil {
		return x.CreatedBy
	}
	return nil
}

func (x *Task_TaskComment) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type Task_TaskHistoryChange struct {
	state         protoimpl.MessageState                        `protogen:"open.v1"`
	Event         Task_TaskHistoryChange_TaskHistoryChangeEvent `protobuf:"varint,1,opt,name=event,proto3,enum=guard.v1.Task_TaskHistoryChange_TaskHistoryChangeEvent" json:"event,omitempty"`
	CreatedBy     *Lookup                                       `protobuf:"bytes,2,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	CreatedAt     *timestamppb.Timestamp                        `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task_TaskHistoryChange) Reset() {
	*x = Task_TaskHistoryChange{}
	mi := &file_message_task_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task_TaskHistoryChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task_TaskHistoryChange) ProtoMessage() {}

func (x *Task_TaskHistoryChange) ProtoReflect() protoreflect.Message {
	mi := &file_message_task_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task_TaskHistoryChange.ProtoReflect.Descriptor instead.
func (*Task_TaskHistoryChange) Descriptor() ([]byte, []int) {
	return file_message_task_proto_rawDescGZIP(), []int{1, 3}
}

func (x *Task_TaskHistoryChange) GetEvent() Task_TaskHistoryChange_TaskHistoryChangeEvent {
	if x != nil {
		return x.Event
	}
	return Task_TaskHistoryChange_TASK_HISTORY_CHANGE_EVENT_UNSPECIFIED
}

func (x *Task_TaskHistoryChange) GetCreatedBy() *Lookup {
	if x != nil {
		return x.CreatedBy
	}
	return nil
}

func (x *Task_TaskHistoryChange) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type SearchTasksRequest_Filter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Priority      TaskPriority           `protobuf:"varint,1,opt,name=priority,proto3,enum=guard.v1.TaskPriority" json:"priority,omitempty"`
	OfficeId      int64                  `protobuf:"varint,2,opt,name=office_id,json=officeId,proto3" json:"office_id,omitempty"`
	ExecutorId    int64                  `protobuf:"varint,3,opt,name=executor_id,json=executorId,proto3" json:"executor_id,omitempty"`
	ViolatorType  ViolatorType           `protobuf:"varint,4,opt,name=violator_type,json=violatorType,proto3,enum=guard.v1.ViolatorType" json:"violator_type,omitempty"`
	Kusp          string                 `protobuf:"bytes,5,opt,name=kusp,proto3" json:"kusp,omitempty"`
	Ud            string                 `protobuf:"bytes,6,opt,name=ud,proto3" json:"ud,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchTasksRequest_Filter) Reset() {
	*x = SearchTasksRequest_Filter{}
	mi := &file_message_task_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchTasksRequest_Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchTasksRequest_Filter) ProtoMessage() {}

func (x *SearchTasksRequest_Filter) ProtoReflect() protoreflect.Message {
	mi := &file_message_task_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchTasksRequest_Filter.ProtoReflect.Descriptor instead.
func (*SearchTasksRequest_Filter) Descriptor() ([]byte, []int) {
	return file_message_task_proto_rawDescGZIP(), []int{4, 0}
}

func (x *SearchTasksRequest_Filter) GetPriority() TaskPriority {
	if x != nil {
		return x.Priority
	}
	return TaskPriority_TASK_PRIORITY_UNSPECIFIED
}

func (x *SearchTasksRequest_Filter) GetOfficeId() int64 {
	if x != nil {
		return x.OfficeId
	}
	return 0
}

func (x *SearchTasksRequest_Filter) GetExecutorId() int64 {
	if x != nil {
		return x.ExecutorId
	}
	return 0
}

func (x *SearchTasksRequest_Filter) GetViolatorType() ViolatorType {
	if x != nil {
		return x.ViolatorType
	}
	return ViolatorType_VIOLATOR_TYPE_UNSPECIFIED
}

func (x *SearchTasksRequest_Filter) GetKusp() string {
	if x != nil {
		return x.Kusp
	}
	return ""
}

func (x *SearchTasksRequest_Filter) GetUd() string {
	if x != nil {
		return x.Ud
	}
	return ""
}

type SearchTasksResponse_TaskLookup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DamageAmount  int64                  `protobuf:"varint,2,opt,name=damage_amount,json=damageAmount,proto3" json:"damage_amount,omitempty"`
	Priority      TaskPriority           `protobuf:"varint,3,opt,name=priority,proto3,enum=guard.v1.TaskPriority" json:"priority,omitempty"`
	Executor      *Lookup                `protobuf:"bytes,4,opt,name=executor,proto3" json:"executor,omitempty"`
	Violator      *Lookup                `protobuf:"bytes,5,opt,name=violator,proto3" json:"violator,omitempty"`
	Office        *Lookup                `protobuf:"bytes,6,opt,name=office,proto3" json:"office,omitempty"`
	CreatedBy     *Lookup                `protobuf:"bytes,7,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	StartDate     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=end_date,json=endDate,proto3,oneof" json:"end_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchTasksResponse_TaskLookup) Reset() {
	*x = SearchTasksResponse_TaskLookup{}
	mi := &file_message_task_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchTasksResponse_TaskLookup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchTasksResponse_TaskLookup) ProtoMessage() {}

func (x *SearchTasksResponse_TaskLookup) ProtoReflect() protoreflect.Message {
	mi := &file_message_task_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchTasksResponse_TaskLookup.ProtoReflect.Descriptor instead.
func (*SearchTasksResponse_TaskLookup) Descriptor() ([]byte, []int) {
	return file_message_task_proto_rawDescGZIP(), []int{5, 0}
}

func (x *SearchTasksResponse_TaskLookup) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SearchTasksResponse_TaskLookup) GetDamageAmount() int64 {
	if x != nil {
		return x.DamageAmount
	}
	return 0
}

func (x *SearchTasksResponse_TaskLookup) GetPriority() TaskPriority {
	if x != nil {
		return x.Priority
	}
	return TaskPriority_TASK_PRIORITY_UNSPECIFIED
}

func (x *SearchTasksResponse_TaskLookup) GetExecutor() *Lookup {
	if x != nil {
		return x.Executor
	}
	return nil
}

func (x *SearchTasksResponse_TaskLookup) GetViolator() *Lookup {
	if x != nil {
		return x.Violator
	}
	return nil
}

func (x *SearchTasksResponse_TaskLookup) GetOffice() *Lookup {
	if x != nil {
		return x.Office
	}
	return nil
}

func (x *SearchTasksResponse_TaskLookup) GetCreatedBy() *Lookup {
	if x != nil {
		return x.CreatedBy
	}
	return nil
}

func (x *SearchTasksResponse_TaskLookup) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *SearchTasksResponse_TaskLookup) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *SearchTasksResponse_TaskLookup) GetEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

var File_message_task_proto protoreflect.FileDescriptor

const file_message_task_proto_rawDesc = "" +
	"\n" +
	"\x12message/task.proto\x12\bguard.v1\x1a\x1fgoogle/api/field_behavior.proto\x1a\x17validate/validate.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x14message/common.proto\"\xe4\x01\n" +
	"\x11CreateTaskRequest\x12/\n" +
	"\rdamage_amount\x18\x01 \x01(\x03B\n" +
	"\xe0A\x02\xfaB\x04\"\x02 \x00R\fdamageAmount\x12A\n" +
	"\bpriority\x18\x02 \x01(\x0e2\x16.guard.v1.TaskPriorityB\r\xe0A\x02\xfaB\a\x82\x01\x04\x10\x01 \x00R\bpriority\x12+\n" +
	"\vexecutor_id\x18\x03 \x01(\x03B\n" +
	"\xe0A\x02\xfaB\x04\"\x02 \x00R\n" +
	"executorId\x12.\n" +
	"\rcreated_by_id\x18\x04 \x01(\x03B\n" +
	"\xe0A\x02\xfaB\x04\"\x02 \x00R\vcreatedById\"\x88\r\n" +
	"\x04Task\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12#\n" +
	"\rdamage_amount\x18\x02 \x01(\x03R\fdamageAmount\x122\n" +
	"\bpriority\x18\x03 \x01(\x0e2\x16.guard.v1.TaskPriorityR\bpriority\x12,\n" +
	"\x06status\x18\x04 \x01(\x0e2\x14.guard.v1.TaskStatusR\x06status\x12,\n" +
	"\bexecutor\x18\x05 \x01(\v2\x10.guard.v1.LookupR\bexecutor\x12,\n" +
	"\bviolator\x18\x06 \x01(\v2\x10.guard.v1.LookupR\bviolator\x12(\n" +
	"\x06office\x18\a \x01(\v2\x10.guard.v1.LookupR\x06office\x12/\n" +
	"\n" +
	"created_by\x18\b \x01(\v2\x10.guard.v1.LookupR\tcreatedBy\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"start_date\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tstartDate\x12:\n" +
	"\bend_date\x18\v \x01(\v2\x1a.google.protobuf.TimestampH\x00R\aendDate\x88\x01\x01\x123\n" +
	"\arefunds\x18\f \x01(\v2\x19.guard.v1.Task.TaskRefundR\arefunds\x12C\n" +
	"\rvud_decisions\x18\r \x01(\v2\x1e.guard.v1.Task.TaskVudDecisionR\fvudDecisions\x126\n" +
	"\bcomments\x18\x0e \x03(\v2\x1a.guard.v1.Task.TaskCommentR\bcomments\x12I\n" +
	"\x0fhistory_changes\x18\x0f \x03(\v2 .guard.v1.Task.TaskHistoryChangeR\x0ehistoryChanges\x1a_\n" +
	"\n" +
	"TaskRefund\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x03R\x06amount\x12\x1d\n" +
	"\acomment\x18\x03 \x01(\tH\x00R\acomment\x88\x01\x01B\n" +
	"\n" +
	"\b_comment\x1a\xcc\x01\n" +
	"\x0fTaskVudDecision\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04kusp\x18\x02 \x01(\tR\x04kusp\x12\x13\n" +
	"\x02ud\x18\x03 \x01(\tH\x00R\x02ud\x88\x01\x01\x125\n" +
	"\x14criminal_case_opened\x18\x04 \x01(\bH\x01R\x12criminalCaseOpened\x88\x01\x01\x12\x1d\n" +
	"\acomment\x18\x05 \x01(\tH\x02R\acomment\x88\x01\x01B\x05\n" +
	"\x03_udB\x17\n" +
	"\x15_criminal_case_openedB\n" +
	"\n" +
	"\b_comment\x1a\xa3\x01\n" +
	"\vTaskComment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x18\n" +
	"\acomment\x18\x02 \x01(\tR\acomment\x12/\n" +
	"\n" +
	"created_by\x18\x03 \x01(\v2\x10.guard.v1.LookupR\tcreatedBy\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x1a\x9f\x03\n" +
	"\x11TaskHistoryChange\x12M\n" +
	"\x05event\x18\x01 \x01(\x0e27.guard.v1.Task.TaskHistoryChange.TaskHistoryChangeEventR\x05event\x12/\n" +
	"\n" +
	"created_by\x18\x02 \x01(\v2\x10.guard.v1.LookupR\tcreatedBy\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xce\x01\n" +
	"\x16TaskHistoryChangeEvent\x12)\n" +
	"%TASK_HISTORY_CHANGE_EVENT_UNSPECIFIED\x10\x00\x12+\n" +
	"'TASK_HISTORY_CHANGE_EVENT_COMMENT_ADDED\x10\x01\x12*\n" +
	"&TASK_HISTORY_CHANGE_EVENT_REFUND_ADDED\x10\x02\x120\n" +
	",TASK_HISTORY_CHANGE_EVENT_VUD_DECISION_ADDED\x10\x03B\v\n" +
	"\t_end_date\"5\n" +
	"\x0fGetTaskResponse\x12\"\n" +
	"\x04task\x18\x01 \x01(\v2\x0e.guard.v1.TaskR\x04task\"\x82\x03\n" +
	"\x11UpdateTaskRequest\x12\x1a\n" +
	"\x02id\x18\x01 \x01(\x03B\n" +
	"\xe0A\x02\xfaB\x04\"\x02 \x00R\x02id\x12(\n" +
	"\rdamage_amount\x18\x02 \x01(\x03H\x00R\fdamageAmount\x88\x01\x01\x12A\n" +
	"\bpriority\x18\x03 \x01(\x0e2\x16.guard.v1.TaskPriorityB\b\xfaB\x05\x82\x01\x02\x10\x01H\x01R\bpriority\x88\x01\x01\x12;\n" +
	"\x06status\x18\x04 \x01(\x0e2\x14.guard.v1.TaskStatusB\b\xfaB\x05\x82\x01\x02\x10\x01H\x02R\x06status\x88\x01\x01\x12:\n" +
	"\bend_date\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampH\x03R\aendDate\x88\x01\x01\x12$\n" +
	"\vexecutor_id\x18\x06 \x01(\x03H\x04R\n" +
	"executorId\x88\x01\x01B\x10\n" +
	"\x0e_damage_amountB\v\n" +
	"\t_priorityB\t\n" +
	"\a_statusB\v\n" +
	"\t_end_dateB\x0e\n" +
	"\f_executor_id\"\x87\x04\n" +
	"\x12SearchTasksRequest\x12\x1e\n" +
	"\x04page\x18\x01 \x01(\x05B\n" +
	"\xe0A\x02\xfaB\x04\x1a\x02(\x01R\x04page\x12%\n" +
	"\bper_page\x18\x02 \x01(\x05B\n" +
	"\xe0A\x02\xfaB\x04\x1a\x02(\x01R\aperPage\x120\n" +
	"\asorting\x18\x03 \x01(\v2\x11.guard.v1.SortingB\x03\xe0A\x02R\asorting\x129\n" +
	"\x06status\x18\x04 \x01(\x0e2\x14.guard.v1.TaskStatusB\v\xe0A\x02\xfaB\x05\x82\x01\x02\x10\x01R\x06status\x12@\n" +
	"\x06filter\x18\x05 \x01(\v2#.guard.v1.SearchTasksRequest.FilterH\x00R\x06filter\x88\x01\x01\x1a\xef\x01\n" +
	"\x06Filter\x12<\n" +
	"\bpriority\x18\x01 \x01(\x0e2\x16.guard.v1.TaskPriorityB\b\xfaB\x05\x82\x01\x02\x10\x01R\bpriority\x12\x1b\n" +
	"\toffice_id\x18\x02 \x01(\x03R\bofficeId\x12\x1f\n" +
	"\vexecutor_id\x18\x03 \x01(\x03R\n" +
	"executorId\x12E\n" +
	"\rviolator_type\x18\x04 \x01(\x0e2\x16.guard.v1.ViolatorTypeB\b\xfaB\x05\x82\x01\x02\x10\x01R\fviolatorType\x12\x12\n" +
	"\x04kusp\x18\x05 \x01(\tR\x04kusp\x12\x0e\n" +
	"\x02ud\x18\x06 \x01(\tR\x02udB\t\n" +
	"\a_filter\"\xd9\x04\n" +
	"\x13SearchTasksResponse\x12>\n" +
	"\x05items\x18\x01 \x03(\v2(.guard.v1.SearchTasksResponse.TaskLookupR\x05items\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x1a\xeb\x03\n" +
	"\n" +
	"TaskLookup\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12#\n" +
	"\rdamage_amount\x18\x02 \x01(\x03R\fdamageAmount\x122\n" +
	"\bpriority\x18\x03 \x01(\x0e2\x16.guard.v1.TaskPriorityR\bpriority\x12,\n" +
	"\bexecutor\x18\x04 \x01(\v2\x10.guard.v1.LookupR\bexecutor\x12,\n" +
	"\bviolator\x18\x05 \x01(\v2\x10.guard.v1.LookupR\bviolator\x12(\n" +
	"\x06office\x18\x06 \x01(\v2\x10.guard.v1.LookupR\x06office\x12/\n" +
	"\n" +
	"created_by\x18\a \x01(\v2\x10.guard.v1.LookupR\tcreatedBy\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"start_date\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tstartDate\x12:\n" +
	"\bend_date\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampH\x00R\aendDate\x88\x01\x01B\v\n" +
	"\t_end_dateB=Z;github.com/gigasigmaslav/guard-panel-api/pkg/api/v1/messageb\x06proto3"

var (
	file_message_task_proto_rawDescOnce sync.Once
	file_message_task_proto_rawDescData []byte
)

func file_message_task_proto_rawDescGZIP() []byte {
	file_message_task_proto_rawDescOnce.Do(func() {
		file_message_task_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_message_task_proto_rawDesc), len(file_message_task_proto_rawDesc)))
	})
	return file_message_task_proto_rawDescData
}

var file_message_task_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_message_task_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_message_task_proto_goTypes = []any{
	(Task_TaskHistoryChange_TaskHistoryChangeEvent)(0), // 0: guard.v1.Task.TaskHistoryChange.TaskHistoryChangeEvent
	(*CreateTaskRequest)(nil),                          // 1: guard.v1.CreateTaskRequest
	(*Task)(nil),                                       // 2: guard.v1.Task
	(*GetTaskResponse)(nil),                            // 3: guard.v1.GetTaskResponse
	(*UpdateTaskRequest)(nil),                          // 4: guard.v1.UpdateTaskRequest
	(*SearchTasksRequest)(nil),                         // 5: guard.v1.SearchTasksRequest
	(*SearchTasksResponse)(nil),                        // 6: guard.v1.SearchTasksResponse
	(*Task_TaskRefund)(nil),                            // 7: guard.v1.Task.TaskRefund
	(*Task_TaskVudDecision)(nil),                       // 8: guard.v1.Task.TaskVudDecision
	(*Task_TaskComment)(nil),                           // 9: guard.v1.Task.TaskComment
	(*Task_TaskHistoryChange)(nil),                     // 10: guard.v1.Task.TaskHistoryChange
	(*SearchTasksRequest_Filter)(nil),                  // 11: guard.v1.SearchTasksRequest.Filter
	(*SearchTasksResponse_TaskLookup)(nil),             // 12: guard.v1.SearchTasksResponse.TaskLookup
	(TaskPriority)(0),                                  // 13: guard.v1.TaskPriority
	(TaskStatus)(0),                                    // 14: guard.v1.TaskStatus
	(*Lookup)(nil),                                     // 15: guard.v1.Lookup
	(*timestamppb.Timestamp)(nil),                      // 16: google.protobuf.Timestamp
	(*Sorting)(nil),                                    // 17: guard.v1.Sorting
	(ViolatorType)(0),                                  // 18: guard.v1.ViolatorType
}
var file_message_task_proto_depIdxs = []int32{
	13, // 0: guard.v1.CreateTaskRequest.priority:type_name -> guard.v1.TaskPriority
	13, // 1: guard.v1.Task.priority:type_name -> guard.v1.TaskPriority
	14, // 2: guard.v1.Task.status:type_name -> guard.v1.TaskStatus
	15, // 3: guard.v1.Task.executor:type_name -> guard.v1.Lookup
	15, // 4: guard.v1.Task.violator:type_name -> guard.v1.Lookup
	15, // 5: guard.v1.Task.office:type_name -> guard.v1.Lookup
	15, // 6: guard.v1.Task.created_by:type_name -> guard.v1.Lookup
	16, // 7: guard.v1.Task.created_at:type_name -> google.protobuf.Timestamp
	16, // 8: guard.v1.Task.start_date:type_name -> google.protobuf.Timestamp
	16, // 9: guard.v1.Task.end_date:type_name -> google.protobuf.Timestamp
	7,  // 10: guard.v1.Task.refunds:type_name -> guard.v1.Task.TaskRefund
	8,  // 11: guard.v1.Task.vud_decisions:type_name -> guard.v1.Task.TaskVudDecision
	9,  // 12: guard.v1.Task.comments:type_name -> guard.v1.Task.TaskComment
	10, // 13: guard.v1.Task.history_changes:type_name -> guard.v1.Task.TaskHistoryChange
	2,  // 14: guard.v1.GetTaskResponse.task:type_name -> guard.v1.Task
	13, // 15: guard.v1.UpdateTaskRequest.priority:type_name -> guard.v1.TaskPriority
	14, // 16: guard.v1.UpdateTaskRequest.status:type_name -> guard.v1.TaskStatus
	16, // 17: guard.v1.UpdateTaskRequest.end_date:type_name -> google.protobuf.Timestamp
	17, // 18: guard.v1.SearchTasksRequest.sorting:type_name -> guard.v1.Sorting
	14, // 19: guard.v1.SearchTasksRequest.status:type_name -> guard.v1.TaskStatus
	11, // 20: guard.v1.SearchTasksRequest.filter:type_name -> guard.v1.SearchTasksRequest.Filter
	12, // 21: guard.v1.SearchTasksResponse.items:type_name -> guard.v1.SearchTasksResponse.TaskLookup
	15, // 22: guard.v1.Task.TaskComment.created_by:type_name -> guard.v1.Lookup
	16, // 23: guard.v1.Task.TaskComment.created_at:type_name -> google.protobuf.Timestamp
	0,  // 24: guard.v1.Task.TaskHistoryChange.event:type_name -> guard.v1.Task.TaskHistoryChange.TaskHistoryChangeEvent
	15, // 25: guard.v1.Task.TaskHistoryChange.created_by:type_name -> guard.v1.Lookup
	16, // 26: guard.v1.Task.TaskHistoryChange.created_at:type_name -> google.protobuf.Timestamp
	13, // 27: guard.v1.SearchTasksRequest.Filter.priority:type_name -> guard.v1.TaskPriority
	18, // 28: guard.v1.SearchTasksRequest.Filter.violator_type:type_name -> guard.v1.ViolatorType
	13, // 29: guard.v1.SearchTasksResponse.TaskLookup.priority:type_name -> guard.v1.TaskPriority
	15, // 30: guard.v1.SearchTasksResponse.TaskLookup.executor:type_name -> guard.v1.Lookup
	15, // 31: guard.v1.SearchTasksResponse.TaskLookup.violator:type_name -> guard.v1.Lookup
	15, // 32: guard.v1.SearchTasksResponse.TaskLookup.office:type_name -> guard.v1.Lookup
	15, // 33: guard.v1.SearchTasksResponse.TaskLookup.created_by:type_name -> guard.v1.Lookup
	16, // 34: guard.v1.SearchTasksResponse.TaskLookup.created_at:type_name -> google.protobuf.Timestamp
	16, // 35: guard.v1.SearchTasksResponse.TaskLookup.start_date:type_name -> google.protobuf.Timestamp
	16, // 36: guard.v1.SearchTasksResponse.TaskLookup.end_date:type_name -> google.protobuf.Timestamp
	37, // [37:37] is the sub-list for method output_type
	37, // [37:37] is the sub-list for method input_type
	37, // [37:37] is the sub-list for extension type_name
	37, // [37:37] is the sub-list for extension extendee
	0,  // [0:37] is the sub-list for field type_name
}

func init() { file_message_task_proto_init() }
func file_message_task_proto_init() {
	if File_message_task_proto != nil {
		return
	}
	file_message_common_proto_init()
	file_message_task_proto_msgTypes[1].OneofWrappers = []any{}
	file_message_task_proto_msgTypes[3].OneofWrappers = []any{}
	file_message_task_proto_msgTypes[4].OneofWrappers = []any{}
	file_message_task_proto_msgTypes[6].OneofWrappers = []any{}
	file_message_task_proto_msgTypes[7].OneofWrappers = []any{}
	file_message_task_proto_msgTypes[11].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_message_task_proto_rawDesc), len(file_message_task_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_message_task_proto_goTypes,
		DependencyIndexes: file_message_task_proto_depIdxs,
		EnumInfos:         file_message_task_proto_enumTypes,
		MessageInfos:      file_message_task_proto_msgTypes,
	}.Build()
	File_message_task_proto = out.File
	file_message_task_proto_goTypes = nil
	file_message_task_proto_depIdxs = nil
}
