// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.0
// source: message/vud-decision.proto

package message

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VudDecision struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TaskId             int64                  `protobuf:"varint,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	CriminalCaseOpened bool                   `protobuf:"varint,3,opt,name=criminal_case_opened,json=criminalCaseOpened,proto3" json:"criminal_case_opened,omitempty"`
	Comment            string                 `protobuf:"bytes,4,opt,name=comment,proto3" json:"comment,omitempty"`
	Kusp               string                 `protobuf:"bytes,5,opt,name=kusp,proto3" json:"kusp,omitempty"`
	Ud                 string                 `protobuf:"bytes,6,opt,name=ud,proto3" json:"ud,omitempty"`
	CreatedBy          *Lookup                `protobuf:"bytes,7,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	CreatedAt          *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *VudDecision) Reset() {
	*x = VudDecision{}
	mi := &file_message_vud_decision_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VudDecision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VudDecision) ProtoMessage() {}

func (x *VudDecision) ProtoReflect() protoreflect.Message {
	mi := &file_message_vud_decision_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VudDecision.ProtoReflect.Descriptor instead.
func (*VudDecision) Descriptor() ([]byte, []int) {
	return file_message_vud_decision_proto_rawDescGZIP(), []int{0}
}

func (x *VudDecision) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *VudDecision) GetTaskId() int64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *VudDecision) GetCriminalCaseOpened() bool {
	if x != nil {
		return x.CriminalCaseOpened
	}
	return false
}

func (x *VudDecision) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *VudDecision) GetKusp() string {
	if x != nil {
		return x.Kusp
	}
	return ""
}

func (x *VudDecision) GetUd() string {
	if x != nil {
		return x.Ud
	}
	return ""
}

func (x *VudDecision) GetCreatedBy() *Lookup {
	if x != nil {
		return x.CreatedBy
	}
	return nil
}

func (x *VudDecision) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type CreateVudDecisionRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	TaskId             int64                  `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Kusp               string                 `protobuf:"bytes,2,opt,name=kusp,proto3" json:"kusp,omitempty"`
	CreatedById        int64                  `protobuf:"varint,3,opt,name=created_by_id,json=createdById,proto3" json:"created_by_id,omitempty"`
	Ud                 *string                `protobuf:"bytes,4,opt,name=ud,proto3,oneof" json:"ud,omitempty"`
	CriminalCaseOpened *bool                  `protobuf:"varint,5,opt,name=criminal_case_opened,json=criminalCaseOpened,proto3,oneof" json:"criminal_case_opened,omitempty"`
	Comment            *string                `protobuf:"bytes,6,opt,name=comment,proto3,oneof" json:"comment,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CreateVudDecisionRequest) Reset() {
	*x = CreateVudDecisionRequest{}
	mi := &file_message_vud_decision_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVudDecisionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVudDecisionRequest) ProtoMessage() {}

func (x *CreateVudDecisionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_vud_decision_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVudDecisionRequest.ProtoReflect.Descriptor instead.
func (*CreateVudDecisionRequest) Descriptor() ([]byte, []int) {
	return file_message_vud_decision_proto_rawDescGZIP(), []int{1}
}

func (x *CreateVudDecisionRequest) GetTaskId() int64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *CreateVudDecisionRequest) GetKusp() string {
	if x != nil {
		return x.Kusp
	}
	return ""
}

func (x *CreateVudDecisionRequest) GetCreatedById() int64 {
	if x != nil {
		return x.CreatedById
	}
	return 0
}

func (x *CreateVudDecisionRequest) GetUd() string {
	if x != nil && x.Ud != nil {
		return *x.Ud
	}
	return ""
}

func (x *CreateVudDecisionRequest) GetCriminalCaseOpened() bool {
	if x != nil && x.CriminalCaseOpened != nil {
		return *x.CriminalCaseOpened
	}
	return false
}

func (x *CreateVudDecisionRequest) GetComment() string {
	if x != nil && x.Comment != nil {
		return *x.Comment
	}
	return ""
}

type UpdateVudDecisionRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Kusp               *string                `protobuf:"bytes,2,opt,name=kusp,proto3,oneof" json:"kusp,omitempty"`
	Ud                 *string                `protobuf:"bytes,3,opt,name=ud,proto3,oneof" json:"ud,omitempty"`
	CriminalCaseOpened *bool                  `protobuf:"varint,4,opt,name=criminal_case_opened,json=criminalCaseOpened,proto3,oneof" json:"criminal_case_opened,omitempty"`
	Comment            *string                `protobuf:"bytes,5,opt,name=comment,proto3,oneof" json:"comment,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *UpdateVudDecisionRequest) Reset() {
	*x = UpdateVudDecisionRequest{}
	mi := &file_message_vud_decision_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateVudDecisionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateVudDecisionRequest) ProtoMessage() {}

func (x *UpdateVudDecisionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_vud_decision_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateVudDecisionRequest.ProtoReflect.Descriptor instead.
func (*UpdateVudDecisionRequest) Descriptor() ([]byte, []int) {
	return file_message_vud_decision_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateVudDecisionRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateVudDecisionRequest) GetKusp() string {
	if x != nil && x.Kusp != nil {
		return *x.Kusp
	}
	return ""
}

func (x *UpdateVudDecisionRequest) GetUd() string {
	if x != nil && x.Ud != nil {
		return *x.Ud
	}
	return ""
}

func (x *UpdateVudDecisionRequest) GetCriminalCaseOpened() bool {
	if x != nil && x.CriminalCaseOpened != nil {
		return *x.CriminalCaseOpened
	}
	return false
}

func (x *UpdateVudDecisionRequest) GetComment() string {
	if x != nil && x.Comment != nil {
		return *x.Comment
	}
	return ""
}

var File_message_vud_decision_proto protoreflect.FileDescriptor

const file_message_vud_decision_proto_rawDesc = "" +
	"\n" +
	"\x1amessage/vud-decision.proto\x12\bguard.v1\x1a\x1fgoogle/api/field_behavior.proto\x1a\x17validate/validate.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x14message/common.proto\"\x92\x02\n" +
	"\vVudDecision\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\x03R\x06taskId\x120\n" +
	"\x14criminal_case_opened\x18\x03 \x01(\bR\x12criminalCaseOpened\x12\x18\n" +
	"\acomment\x18\x04 \x01(\tR\acomment\x12\x12\n" +
	"\x04kusp\x18\x05 \x01(\tR\x04kusp\x12\x0e\n" +
	"\x02ud\x18\x06 \x01(\tR\x02ud\x12/\n" +
	"\n" +
	"created_by\x18\a \x01(\v2\x10.guard.v1.LookupR\tcreatedBy\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xaf\x02\n" +
	"\x18CreateVudDecisionRequest\x12#\n" +
	"\atask_id\x18\x01 \x01(\x03B\n" +
	"\xe0A\x02\xfaB\x04\"\x02 \x00R\x06taskId\x12\x1e\n" +
	"\x04kusp\x18\x02 \x01(\tB\n" +
	"\xe0A\x02\xfaB\x04r\x02\x18\n" +
	"R\x04kusp\x12.\n" +
	"\rcreated_by_id\x18\x03 \x01(\x03B\n" +
	"\xe0A\x02\xfaB\x04\"\x02 \x00R\vcreatedById\x12\x1c\n" +
	"\x02ud\x18\x04 \x01(\tB\a\xfaB\x04r\x02\x18\x19H\x00R\x02ud\x88\x01\x01\x125\n" +
	"\x14criminal_case_opened\x18\x05 \x01(\bH\x01R\x12criminalCaseOpened\x88\x01\x01\x12\x1d\n" +
	"\acomment\x18\x06 \x01(\tH\x02R\acomment\x88\x01\x01B\x05\n" +
	"\x03_udB\x17\n" +
	"\x15_criminal_case_openedB\n" +
	"\n" +
	"\b_comment\"\x81\x02\n" +
	"\x18UpdateVudDecisionRequest\x12\x1a\n" +
	"\x02id\x18\x01 \x01(\x03B\n" +
	"\xe0A\x02\xfaB\x04\"\x02 \x00R\x02id\x12 \n" +
	"\x04kusp\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x18\n" +
	"H\x00R\x04kusp\x88\x01\x01\x12\x1c\n" +
	"\x02ud\x18\x03 \x01(\tB\a\xfaB\x04r\x02\x18\x19H\x01R\x02ud\x88\x01\x01\x125\n" +
	"\x14criminal_case_opened\x18\x04 \x01(\bH\x02R\x12criminalCaseOpened\x88\x01\x01\x12\x1d\n" +
	"\acomment\x18\x05 \x01(\tH\x03R\acomment\x88\x01\x01B\a\n" +
	"\x05_kuspB\x05\n" +
	"\x03_udB\x17\n" +
	"\x15_criminal_case_openedB\n" +
	"\n" +
	"\b_commentB=Z;github.com/gigasigmaslav/guard-panel-api/pkg/api/v1/messageb\x06proto3"

var (
	file_message_vud_decision_proto_rawDescOnce sync.Once
	file_message_vud_decision_proto_rawDescData []byte
)

func file_message_vud_decision_proto_rawDescGZIP() []byte {
	file_message_vud_decision_proto_rawDescOnce.Do(func() {
		file_message_vud_decision_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_message_vud_decision_proto_rawDesc), len(file_message_vud_decision_proto_rawDesc)))
	})
	return file_message_vud_decision_proto_rawDescData
}

var file_message_vud_decision_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_message_vud_decision_proto_goTypes = []any{
	(*VudDecision)(nil),              // 0: guard.v1.VudDecision
	(*CreateVudDecisionRequest)(nil), // 1: guard.v1.CreateVudDecisionRequest
	(*UpdateVudDecisionRequest)(nil), // 2: guard.v1.UpdateVudDecisionRequest
	(*Lookup)(nil),                   // 3: guard.v1.Lookup
	(*timestamppb.Timestamp)(nil),    // 4: google.protobuf.Timestamp
}
var file_message_vud_decision_proto_depIdxs = []int32{
	3, // 0: guard.v1.VudDecision.created_by:type_name -> guard.v1.Lookup
	4, // 1: guard.v1.VudDecision.created_at:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_message_vud_decision_proto_init() }
func file_message_vud_decision_proto_init() {
	if File_message_vud_decision_proto != nil {
		return
	}
	file_message_common_proto_init()
	file_message_vud_decision_proto_msgTypes[1].OneofWrappers = []any{}
	file_message_vud_decision_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_message_vud_decision_proto_rawDesc), len(file_message_vud_decision_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_message_vud_decision_proto_goTypes,
		DependencyIndexes: file_message_vud_decision_proto_depIdxs,
		MessageInfos:      file_message_vud_decision_proto_msgTypes,
	}.Build()
	File_message_vud_decision_proto = out.File
	file_message_vud_decision_proto_goTypes = nil
	file_message_vud_decision_proto_depIdxs = nil
}
