// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: message/vud-decision.proto

package message

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on VudDecision with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *VudDecision) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on VudDecision with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in VudDecisionMultiError, or
// nil if none found.
func (m *VudDecision) ValidateAll() error {
	return m.validate(true)
}

func (m *VudDecision) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for TaskId

	// no validation rules for CriminalCaseOpened

	// no validation rules for Comment

	// no validation rules for Kusp

	// no validation rules for Ud

	if all {
		switch v := interface{}(m.GetCreatedBy()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, VudDecisionValidationError{
					field:  "CreatedBy",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, VudDecisionValidationError{
					field:  "CreatedBy",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCreatedBy()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return VudDecisionValidationError{
				field:  "CreatedBy",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetCreatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, VudDecisionValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, VudDecisionValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCreatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return VudDecisionValidationError{
				field:  "CreatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return VudDecisionMultiError(errors)
	}

	return nil
}

// VudDecisionMultiError is an error wrapping multiple validation errors
// returned by VudDecision.ValidateAll() if the designated constraints aren't met.
type VudDecisionMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m VudDecisionMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m VudDecisionMultiError) AllErrors() []error { return m }

// VudDecisionValidationError is the validation error returned by
// VudDecision.Validate if the designated constraints aren't met.
type VudDecisionValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e VudDecisionValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e VudDecisionValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e VudDecisionValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e VudDecisionValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e VudDecisionValidationError) ErrorName() string { return "VudDecisionValidationError" }

// Error satisfies the builtin error interface
func (e VudDecisionValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sVudDecision.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = VudDecisionValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = VudDecisionValidationError{}

// Validate checks the field values on CreateVudDecisionRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateVudDecisionRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateVudDecisionRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateVudDecisionRequestMultiError, or nil if none found.
func (m *CreateVudDecisionRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateVudDecisionRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetTaskId() <= 0 {
		err := CreateVudDecisionRequestValidationError{
			field:  "TaskId",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetKusp()) > 10 {
		err := CreateVudDecisionRequestValidationError{
			field:  "Kusp",
			reason: "value length must be at most 10 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetCreatedById() <= 0 {
		err := CreateVudDecisionRequestValidationError{
			field:  "CreatedById",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.Ud != nil {

		if utf8.RuneCountInString(m.GetUd()) > 25 {
			err := CreateVudDecisionRequestValidationError{
				field:  "Ud",
				reason: "value length must be at most 25 runes",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	}

	if m.CriminalCaseOpened != nil {
		// no validation rules for CriminalCaseOpened
	}

	if m.Comment != nil {
		// no validation rules for Comment
	}

	if len(errors) > 0 {
		return CreateVudDecisionRequestMultiError(errors)
	}

	return nil
}

// CreateVudDecisionRequestMultiError is an error wrapping multiple validation
// errors returned by CreateVudDecisionRequest.ValidateAll() if the designated
// constraints aren't met.
type CreateVudDecisionRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateVudDecisionRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateVudDecisionRequestMultiError) AllErrors() []error { return m }

// CreateVudDecisionRequestValidationError is the validation error returned by
// CreateVudDecisionRequest.Validate if the designated constraints aren't met.
type CreateVudDecisionRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateVudDecisionRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateVudDecisionRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateVudDecisionRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateVudDecisionRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateVudDecisionRequestValidationError) ErrorName() string {
	return "CreateVudDecisionRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CreateVudDecisionRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateVudDecisionRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateVudDecisionRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateVudDecisionRequestValidationError{}

// Validate checks the field values on UpdateVudDecisionRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateVudDecisionRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateVudDecisionRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateVudDecisionRequestMultiError, or nil if none found.
func (m *UpdateVudDecisionRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateVudDecisionRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetId() <= 0 {
		err := UpdateVudDecisionRequestValidationError{
			field:  "Id",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.Kusp != nil {

		if utf8.RuneCountInString(m.GetKusp()) > 10 {
			err := UpdateVudDecisionRequestValidationError{
				field:  "Kusp",
				reason: "value length must be at most 10 runes",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	}

	if m.Ud != nil {

		if utf8.RuneCountInString(m.GetUd()) > 25 {
			err := UpdateVudDecisionRequestValidationError{
				field:  "Ud",
				reason: "value length must be at most 25 runes",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	}

	if m.CriminalCaseOpened != nil {
		// no validation rules for CriminalCaseOpened
	}

	if m.Comment != nil {
		// no validation rules for Comment
	}

	if len(errors) > 0 {
		return UpdateVudDecisionRequestMultiError(errors)
	}

	return nil
}

// UpdateVudDecisionRequestMultiError is an error wrapping multiple validation
// errors returned by UpdateVudDecisionRequest.ValidateAll() if the designated
// constraints aren't met.
type UpdateVudDecisionRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateVudDecisionRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateVudDecisionRequestMultiError) AllErrors() []error { return m }

// UpdateVudDecisionRequestValidationError is the validation error returned by
// UpdateVudDecisionRequest.Validate if the designated constraints aren't met.
type UpdateVudDecisionRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateVudDecisionRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateVudDecisionRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateVudDecisionRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateVudDecisionRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateVudDecisionRequestValidationError) ErrorName() string {
	return "UpdateVudDecisionRequestValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateVudDecisionRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateVudDecisionRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateVudDecisionRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateVudDecisionRequestValidationError{}
