// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.32.0
// source: guard-panel-api.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GuardPanelService_Stub_FullMethodName = "/api.v1.guardpanelservice.GuardPanelService/Stub"
)

// GuardPanelServiceClient is the client API for GuardPanelService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GuardPanelServiceClient interface {
	Stub(ctx context.Context, in *StubRequest, opts ...grpc.CallOption) (*StubResponse, error)
}

type guardPanelServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGuardPanelServiceClient(cc grpc.ClientConnInterface) GuardPanelServiceClient {
	return &guardPanelServiceClient{cc}
}

func (c *guardPanelServiceClient) Stub(ctx context.Context, in *StubRequest, opts ...grpc.CallOption) (*StubResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StubResponse)
	err := c.cc.Invoke(ctx, GuardPanelService_Stub_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GuardPanelServiceServer is the server API for GuardPanelService service.
// All implementations must embed UnimplementedGuardPanelServiceServer
// for forward compatibility.
type GuardPanelServiceServer interface {
	Stub(context.Context, *StubRequest) (*StubResponse, error)
	mustEmbedUnimplementedGuardPanelServiceServer()
}

// UnimplementedGuardPanelServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGuardPanelServiceServer struct{}

func (UnimplementedGuardPanelServiceServer) Stub(context.Context, *StubRequest) (*StubResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Stub not implemented")
}
func (UnimplementedGuardPanelServiceServer) mustEmbedUnimplementedGuardPanelServiceServer() {}
func (UnimplementedGuardPanelServiceServer) testEmbeddedByValue()                           {}

// UnsafeGuardPanelServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GuardPanelServiceServer will
// result in compilation errors.
type UnsafeGuardPanelServiceServer interface {
	mustEmbedUnimplementedGuardPanelServiceServer()
}

func RegisterGuardPanelServiceServer(s grpc.ServiceRegistrar, srv GuardPanelServiceServer) {
	// If the following call panics, it indicates UnimplementedGuardPanelServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GuardPanelService_ServiceDesc, srv)
}

func _GuardPanelService_Stub_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StubRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuardPanelServiceServer).Stub(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GuardPanelService_Stub_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuardPanelServiceServer).Stub(ctx, req.(*StubRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GuardPanelService_ServiceDesc is the grpc.ServiceDesc for GuardPanelService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GuardPanelService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.v1.guardpanelservice.GuardPanelService",
	HandlerType: (*GuardPanelServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Stub",
			Handler:    _GuardPanelService_Stub_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "guard-panel-api.proto",
}
