// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: guard-panel-api.proto

package api

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on StubRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *StubRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on StubRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in StubRequestMultiError, or
// nil if none found.
func (m *StubRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *StubRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return StubRequestMultiError(errors)
	}

	return nil
}

// StubRequestMultiError is an error wrapping multiple validation errors
// returned by StubRequest.ValidateAll() if the designated constraints aren't met.
type StubRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m StubRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m StubRequestMultiError) AllErrors() []error { return m }

// StubRequestValidationError is the validation error returned by
// StubRequest.Validate if the designated constraints aren't met.
type StubRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e StubRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e StubRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e StubRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e StubRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e StubRequestValidationError) ErrorName() string { return "StubRequestValidationError" }

// Error satisfies the builtin error interface
func (e StubRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sStubRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = StubRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = StubRequestValidationError{}

// Validate checks the field values on StubResponse with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *StubResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on StubResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in StubResponseMultiError, or
// nil if none found.
func (m *StubResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *StubResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Message

	if len(errors) > 0 {
		return StubResponseMultiError(errors)
	}

	return nil
}

// StubResponseMultiError is an error wrapping multiple validation errors
// returned by StubResponse.ValidateAll() if the designated constraints aren't met.
type StubResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m StubResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m StubResponseMultiError) AllErrors() []error { return m }

// StubResponseValidationError is the validation error returned by
// StubResponse.Validate if the designated constraints aren't met.
type StubResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e StubResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e StubResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e StubResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e StubResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e StubResponseValidationError) ErrorName() string { return "StubResponseValidationError" }

// Error satisfies the builtin error interface
func (e StubResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sStubResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = StubResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = StubResponseValidationError{}
