// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.0
// source: guard-panel-api.proto

package api

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StubRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StubRequest) Reset() {
	*x = StubRequest{}
	mi := &file_guard_panel_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StubRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StubRequest) ProtoMessage() {}

func (x *StubRequest) ProtoReflect() protoreflect.Message {
	mi := &file_guard_panel_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StubRequest.ProtoReflect.Descriptor instead.
func (*StubRequest) Descriptor() ([]byte, []int) {
	return file_guard_panel_api_proto_rawDescGZIP(), []int{0}
}

type StubResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StubResponse) Reset() {
	*x = StubResponse{}
	mi := &file_guard_panel_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StubResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StubResponse) ProtoMessage() {}

func (x *StubResponse) ProtoReflect() protoreflect.Message {
	mi := &file_guard_panel_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StubResponse.ProtoReflect.Descriptor instead.
func (*StubResponse) Descriptor() ([]byte, []int) {
	return file_guard_panel_api_proto_rawDescGZIP(), []int{1}
}

func (x *StubResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_guard_panel_api_proto protoreflect.FileDescriptor

const file_guard_panel_api_proto_rawDesc = "" +
	"\n" +
	"\x15guard-panel-api.proto\x12\x18api.v1.guardpanelservice\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a\x17validate/validate.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\r\n" +
	"\vStubRequest\"(\n" +
	"\fStubResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\x80\x01\n" +
	"\x11GuardPanelService\x12k\n" +
	"\x04Stub\x12%.api.v1.guardpanelservice.StubRequest\x1a&.api.v1.guardpanelservice.StubResponse\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/api/v1/stubBw\x92Ad\x12>\n" +
	"\x17Guard panel API service\x12\x1cSecurity service taskbar API2\x051.0.02\x10application/json:\x10application/jsonZ\x0epkg/api/v1;apib\x06proto3"

var (
	file_guard_panel_api_proto_rawDescOnce sync.Once
	file_guard_panel_api_proto_rawDescData []byte
)

func file_guard_panel_api_proto_rawDescGZIP() []byte {
	file_guard_panel_api_proto_rawDescOnce.Do(func() {
		file_guard_panel_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_guard_panel_api_proto_rawDesc), len(file_guard_panel_api_proto_rawDesc)))
	})
	return file_guard_panel_api_proto_rawDescData
}

var file_guard_panel_api_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_guard_panel_api_proto_goTypes = []any{
	(*StubRequest)(nil),  // 0: api.v1.guardpanelservice.StubRequest
	(*StubResponse)(nil), // 1: api.v1.guardpanelservice.StubResponse
}
var file_guard_panel_api_proto_depIdxs = []int32{
	0, // 0: api.v1.guardpanelservice.GuardPanelService.Stub:input_type -> api.v1.guardpanelservice.StubRequest
	1, // 1: api.v1.guardpanelservice.GuardPanelService.Stub:output_type -> api.v1.guardpanelservice.StubResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_guard_panel_api_proto_init() }
func file_guard_panel_api_proto_init() {
	if File_guard_panel_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_guard_panel_api_proto_rawDesc), len(file_guard_panel_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_guard_panel_api_proto_goTypes,
		DependencyIndexes: file_guard_panel_api_proto_depIdxs,
		MessageInfos:      file_guard_panel_api_proto_msgTypes,
	}.Build()
	File_guard_panel_api_proto = out.File
	file_guard_panel_api_proto_goTypes = nil
	file_guard_panel_api_proto_depIdxs = nil
}
